import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { errorResponse, requireApiUser, verifySameOrigin } from "@/lib/api";
import { db } from "@/lib/db";
import { approvalRequests } from "@/lib/db/schema";
import { RelayError } from "@/lib/errors";
import { decideApproval } from "@/lib/v2/approvals";
import { actionIntentSchema, type ApprovalScope } from "@/lib/v2/contracts";
import { operatorContext } from "@/lib/v2/dashboard";
import { completePasswordStepUp, createStepUpChallenge } from "@/lib/v2/identity";
import { requireV2PlatformBindings } from "@/lib/v2/platform-bindings";

const inputSchema = z.object({ requestId: z.string().regex(/^apr_/), decision: z.enum(["APPROVE", "DENY"]), scopeKind: z.enum(["once", "task", "session"]).default("once"), password: z.string().min(1).max(200), reason: z.string().max(500).optional().nullable() }).strict();
export async function POST(request: Request) { try { if (!verifySameOrigin(request)) throw new RelayError("INVALID_CREDENTIAL", "Cross-origin operator mutation denied.", undefined, 403); const user = await requireApiUser(); const operator = await operatorContext(user.accountId, user.id); const input = inputSchema.parse(await request.json()); const [approval] = await db().select().from(approvalRequests).where(and(eq(approvalRequests.accountId, user.accountId), eq(approvalRequests.id, input.requestId), eq(approvalRequests.status, "PENDING"))).limit(1); if (!approval) throw new RelayError("INVALID_INPUT", "Pending approval was not found.", undefined, 404); const action = actionIntentSchema.parse(approval.actionSnapshot); let scope: ApprovalScope | undefined; if (input.decision === "APPROVE") { if (input.scopeKind === "once") scope = { kind: "once", actionHash: action.canonicalHash }; else if (input.scopeKind === "task") scope = { kind: "task", taskId: action.taskId, capability: action.capability, resource: action.resource, maxUses: approval.maxUses }; else { if (!approval.sessionId) throw new RelayError("INVALID_INPUT", "This request has no session scope."); scope = { kind: "session", sessionId: approval.sessionId, capability: action.capability, resource: action.resource, maxUses: approval.maxUses }; } } const actionClass = `approval:${approval.id}:${input.decision}`; const challenge = await createStepUpChallenge({ accountId: user.accountId, principalId: operator.principalId, actionClass, actionHash: approval.actionHash, authenticationMethod: "password" }); const completed = await completePasswordStepUp({ accountId: user.accountId, principalId: operator.principalId, secret: challenge.secret, password: input.password, actionClass, actionHash: approval.actionHash }); const result = await decideApproval({ accountId: user.accountId, requestId: approval.id, principalId: operator.principalId, decision: input.decision, scope, reason: input.reason ?? undefined, authenticationEvidence: { sessionId: completed.id, method: "password", authenticatedAt: completed.consumedAt!, stepUpChallengeId: completed.id } }, requireV2PlatformBindings().signer); return Response.json(result); } catch (error) { return errorResponse(error); } }
