import { generateKeyPairSync, sign } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { agentDelegations, budgets, capabilityLeases, delegatedAuthorities, delegationBudgetAllocations, memories, v2Tasks } from "@/lib/db/schema";
import { id } from "@/lib/ids";
import { createBudget, reserveBudget } from "@/lib/v2/budgets";
import { canonicalHash, type ActionIntent } from "@/lib/v2/contracts";
import { claimDelegatedAuthority, completeAgentDelegation, createAgentDelegation, exportDelegationProvenance, getDelegatedContext, revokeAgentDelegation } from "@/lib/v2/delegations";
import { createLocalEd25519Signer, verifyAuditSignature } from "@/lib/v2/evidence";
import { createWorkloadBootstrap, exchangeWorkloadBootstrap, issueCapabilityLease, revokeLease } from "@/lib/v2/leases";
import { ingestVerifiedEvent, publishEventRoute } from "@/lib/v2/orchestration";
import { activateV2Agent, createV2Agent, issueAgentPassport } from "@/lib/v2/passports";
import { evaluatePolicy, publishRelaySafetyPolicy, registerCapabilityDefinition } from "@/lib/v2/policy";
import { registerRuntimeClient } from "@/lib/v2/runtime-clients";
import { cleanupDatabase, freshDatabase, secondAccount } from "../helpers";

const ownership = { resolveOwnership: async ({ accountId }: { accountId: string }) => ({ name: "resource.account_id", value: accountId, authoritative: true, observedAt: new Date(Date.now() - 100).toISOString(), expiresAt: new Date(Date.now() + 60_000).toISOString(), sourceRevision: "delegation:1" }) };
function makeAction(input: { accountId: string; agentId: string; runtimeClientId: string; taskId: string; capability: string; resourceType: string; resourceId: string; parameters: Record<string, unknown> }): ActionIntent { const material = { capability: { name: input.capability, version: "1.0" }, resource: { type: input.resourceType, ids: [input.resourceId], attributes: { accountId: input.accountId } }, parameters: input.parameters }; return { schemaVersion: "relay.action-intent.v2", id: id("act"), accountId: input.accountId, agentId: input.agentId, runtimeClientId: input.runtimeClientId, taskId: input.taskId, ...material, idempotencyKey: crypto.randomUUID(), createdAt: new Date().toISOString(), canonicalHash: canonicalHash(material) }; }
async function workload(input: { accountId: string; agentId: string; runtimeClientId: string; taskId: string }, signer: ReturnType<typeof createLocalEd25519Signer>) { const pair = generateKeyPairSync("ed25519"); const bootstrap = await createWorkloadBootstrap({ ...input, providerId: "relay-managed", assurance: "managed-equivalent", audience: "relay-managed", publicKeyPem: pair.publicKey.export({ type: "spki", format: "pem" }).toString() }, signer); return await exchangeWorkloadBootstrap({ accountId: input.accountId, secret: bootstrap.secret, proofSignature: sign(null, Buffer.from(bootstrap.challenge), pair.privateKey).toString("base64url") }, signer); }

async function setup() {
  const identity = await freshDatabase(); const signer = createLocalEd25519Signer("delegation-test-key"); const resolver = { publicKeyForKeyId: async (keyId: string) => keyId === signer.keyId ? await signer.publicKeyPem() : undefined }; const parentRuntime = await registerRuntimeClient({ accountId: identity.accountId, actorPrincipalId: identity.principalId, displayName: "Parent runtime", selfDeclaredProduct: "custom" }, signer); const childRuntime = await registerRuntimeClient({ accountId: identity.accountId, actorPrincipalId: identity.principalId, displayName: "Child runtime", selfDeclaredProduct: "custom" }, signer);
  await registerCapabilityDefinition({ name: "agents.task.delegate", version: "1.0", domain: "agents", description: "Delegate bounded work", effectClass: "external_write", riskClass: "medium", resourceType: "task", inputSchema: {}, outputSchema: {} }, signer); await registerCapabilityDefinition({ name: "records.item.read", version: "1.0", domain: "records", description: "Read bounded record", effectClass: "read", riskClass: "low", resourceType: "record", inputSchema: {}, outputSchema: {} }, signer); await publishRelaySafetyPolicy({ name: "delegation-safety", rules: [{ id: "delegate", effect: "ALLOW", match: { capability: { name: "agents.task.delegate", version: "1.0" } }, reasonCode: "ALLOWED_BY_POLICY", limits: { calls: 20 } }, { id: "read", effect: "ALLOW", match: { capability: { name: "records.item.read", version: "1.0" } }, reasonCode: "ALLOWED_BY_POLICY", limits: { calls: 20 } }] }, signer);
  const parent = await createV2Agent({ accountId: identity.accountId, ownerPrincipalId: identity.principalId, name: "Parent Agent" }, signer); const child = await createV2Agent({ accountId: identity.accountId, ownerPrincipalId: identity.principalId, name: "Child Agent" }, signer); const policy = { trustTier: "HIGH_ASSURANCE" as const, capabilityEligibility: [{ name: "agents.task.delegate", version: "1.0" }, { name: "records.item.read", version: "1.0" }], policyReferences: ["delegation-safety"], budgetReferences: [], allowedEnvironments: { providerIds: ["relay-managed"], minimumAssurance: "managed-equivalent" as const }, dataAccess: [{ classification: "confidential" as const, resourceTypes: ["memory"] }], expiresAt: "2099-01-01T00:00:00.000Z" }; for (const agent of [parent, child]) { await issueAgentPassport({ accountId: identity.accountId, agentId: agent.agentId, ownerPrincipalId: identity.principalId, policy }, signer); await activateV2Agent({ accountId: identity.accountId, agentId: agent.agentId, actorPrincipalId: identity.principalId }, signer); }
  await publishEventRoute({ accountId: identity.accountId, actorPrincipalId: identity.principalId, name: "parent-work", source: "https://delegation.test/events", eventType: "parent.work", agentId: parent.agentId }, signer); const event = await ingestVerifiedEvent({ envelope: { specversion: "1.0", id: crypto.randomUUID(), source: "https://delegation.test/events", type: "parent.work", time: new Date().toISOString(), accountid: identity.accountId, classification: "confidential", correlationid: crypto.randomUUID(), dedupekey: crypto.randomUUID(), schemaversion: "relay.event.v2", signaturestatus: "verified" }, rawBody: new Uint8Array(), headers: {} }, { verify: async () => ({ valid: true }) }, signer); const parentTaskId = event.taskIds[0]!; await db().update(v2Tasks).set({ status: "RUNNING" }).where(eq(v2Tasks.id, parentTaskId)); const parentWorkload = await workload({ accountId: identity.accountId, agentId: parent.agentId, runtimeClientId: parentRuntime.runtimeClientId, taskId: parentTaskId }, signer);
  const authorityAction = makeAction({ accountId: identity.accountId, agentId: parent.agentId, runtimeClientId: parentRuntime.runtimeClientId, taskId: parentTaskId, capability: "records.item.read", resourceType: "record", resourceId: "record-set-1", parameters: { query: "bounded" } }); await evaluatePolicy({ accountId: identity.accountId, action: authorityAction, resourceResolver: ownership }, signer); const authorityLease = await issueCapabilityLease({ accountId: identity.accountId, action: authorityAction, workloadId: parentWorkload.workloadId, workloadIdentityToken: parentWorkload.token, audience: "relay-managed", maxCalls: 3 }, signer, resolver);
  const includedMemoryId = id("mem"); const excludedMemoryId = id("mem"); await db().insert(memories).values([{ id: includedMemoryId, accountId: identity.accountId, createdByAgentId: parent.agentId, scope: "AGENT_PRIVATE", type: "FACT", content: "declared context", source: "test" }, { id: excludedMemoryId, accountId: identity.accountId, createdByAgentId: parent.agentId, scope: "AGENT_PRIVATE", type: "FACT", content: "must stay private", source: "test" }]); const parentBudget = await createBudget({ accountId: identity.accountId, actorPrincipalId: identity.principalId, scope: "TASK", scopeId: parentTaskId, dimension: "TOKENS", unit: "token", hardLimit: "100" }, signer);
  return { ...identity, signer, resolver, parentAgentId: parent.agentId, childAgentId: child.agentId, parentRuntimeClientId: parentRuntime.runtimeClientId, childRuntimeClientId: childRuntime.runtimeClientId, parentTaskId, parentWorkload, authorityAction, authorityLease, includedMemoryId, excludedMemoryId, parentBudgetId: parentBudget.budgetId };
}

async function delegate(fixture: Awaited<ReturnType<typeof setup>>, input: { maxCalls?: number; childAgentId?: string; suffix?: string } = {}) { const request = { childAgentId: input.childAgentId ?? fixture.childAgentId, objective: "Read the selected record and return evidence.", authorities: [{ parentLeaseId: fixture.authorityLease.leaseId, maxCalls: input.maxCalls ?? 2 }], contextMemoryIds: [fixture.includedMemoryId], budgets: [{ parentBudgetId: fixture.parentBudgetId, amount: "25" }] }; const action = makeAction({ accountId: fixture.accountId, agentId: fixture.parentAgentId, runtimeClientId: fixture.parentRuntimeClientId, taskId: fixture.parentTaskId, capability: "agents.task.delegate", resourceType: "task", resourceId: fixture.parentTaskId, parameters: request }); await evaluatePolicy({ accountId: fixture.accountId, action, resourceResolver: ownership }, fixture.signer); const authorization = await issueCapabilityLease({ accountId: fixture.accountId, action, workloadId: fixture.parentWorkload.workloadId, workloadIdentityToken: fixture.parentWorkload.token, audience: "relay-managed", maxCalls: 1 }, fixture.signer, fixture.resolver); const created = await createAgentDelegation({ accountId: fixture.accountId, action, authorizationLeaseToken: authorization.token, expectedAudience: "relay-managed", expectedWorkloadId: fixture.parentWorkload.workloadId, request, idempotencyKey: `delegation-${input.suffix ?? crypto.randomUUID()}` }, fixture.signer, fixture.resolver); return { request, action, authorization, created }; }

describe("WO-19 same-account Agent delegation", () => {
  afterEach(cleanupDatabase);

  it("creates an acyclic child task with only declared context, bounded authority, and a child budget", async () => { const fixture = await setup(); const result = await delegate(fixture); const context = await getDelegatedContext({ accountId: fixture.accountId, delegationId: result.created.delegationId, childAgentId: fixture.childAgentId }); expect(context).toEqual([expect.objectContaining({ sourceMemoryId: fixture.includedMemoryId, content: "declared context" })]); expect(JSON.stringify(context)).not.toContain("must stay private"); const [delegation] = await db().select().from(agentDelegations).where(eq(agentDelegations.id, result.created.delegationId)); expect(delegation).toMatchObject({ parentTaskId: fixture.parentTaskId, childTaskId: result.created.childTaskId, depth: 1, status: "ACTIVE" }); const [allocation] = await db().select().from(delegationBudgetAllocations).where(eq(delegationBudgetAllocations.delegationId, result.created.delegationId)); expect(allocation).toMatchObject({ parentBudgetId: fixture.parentBudgetId, amount: "25.000000000" }); const [childBudget] = await db().select().from(budgets).where(eq(budgets.id, allocation!.childBudgetId)); expect(childBudget).toMatchObject({ scope: "DELEGATION", scopeId: result.created.delegationId, hardLimit: "25.000000000" }); });

  it("claims authority once, cannot amplify parent calls, and parent lease revoke cascades", async () => { const fixture = await setup(); const result = await delegate(fixture); const [authority] = await db().select().from(delegatedAuthorities).where(eq(delegatedAuthorities.delegationId, result.created.delegationId)); const childWorkload = await workload({ accountId: fixture.accountId, agentId: fixture.childAgentId, runtimeClientId: fixture.childRuntimeClientId, taskId: result.created.childTaskId }, fixture.signer); const childAction = makeAction({ accountId: fixture.accountId, agentId: fixture.childAgentId, runtimeClientId: fixture.childRuntimeClientId, taskId: result.created.childTaskId, capability: "records.item.read", resourceType: "record", resourceId: "record-set-1", parameters: { query: "child" } }); await evaluatePolicy({ accountId: fixture.accountId, action: childAction, resourceResolver: ownership }, fixture.signer); const childLease = await claimDelegatedAuthority({ accountId: fixture.accountId, delegationId: result.created.delegationId, authorityId: authority!.id, action: childAction, workloadId: childWorkload.workloadId, workloadIdentityToken: childWorkload.token, audience: "relay-managed", maxCalls: 2 }, fixture.signer, fixture.resolver); await expect(claimDelegatedAuthority({ accountId: fixture.accountId, delegationId: result.created.delegationId, authorityId: authority!.id, action: childAction, workloadId: childWorkload.workloadId, workloadIdentityToken: childWorkload.token, audience: "relay-managed", maxCalls: 2 }, fixture.signer, fixture.resolver)).rejects.toMatchObject({ status: 403 }); await revokeLease({ accountId: fixture.accountId, leaseId: fixture.authorityLease.leaseId, reason: "parent revoked" }, fixture.signer); const [stored] = await db().select().from(capabilityLeases).where(eq(capabilityLeases.id, childLease.leaseId)); expect(stored?.status).toBe("REVOKED"); });

  it("rejects cycles and already-promised authority or budget amplification", async () => { const fixture = await setup(); await expect(delegate(fixture, { childAgentId: fixture.parentAgentId, suffix: "self" })).rejects.toMatchObject({ status: 403 }); await delegate(fixture, { maxCalls: 2, suffix: "first" }); await expect(delegate(fixture, { maxCalls: 2, suffix: "second" })).rejects.toMatchObject({ status: 403 }); const [parent] = await db().select().from(capabilityLeases).where(eq(capabilityLeases.id, fixture.authorityLease.leaseId)); expect(parent).toMatchObject({ maxCalls: 3, delegatedCallCount: 0 }); });

  it("uses only delegation-derived budgets for child reservations", async () => { const fixture = await setup(); const result = await delegate(fixture); const [allocation] = await db().select().from(delegationBudgetAllocations).where(eq(delegationBudgetAllocations.delegationId, result.created.delegationId)); await expect(reserveBudget({ accountId: fixture.accountId, leafBudgetId: allocation!.childBudgetId, agentId: fixture.childAgentId, taskId: result.created.childTaskId, actionIntentId: id("act"), delegationId: result.created.delegationId, amount: "20", idempotencyKey: "child-budget", expiresAt: new Date(Date.now() + 45_000).toISOString() }, fixture.signer)).resolves.toMatchObject({ status: "RESERVED" }); await expect(reserveBudget({ accountId: fixture.accountId, leafBudgetId: allocation!.childBudgetId, agentId: fixture.childAgentId, taskId: result.created.childTaskId, actionIntentId: id("act"), delegationId: "dlg_wrong000", amount: "1", idempotencyKey: "wrong-delegation", expiresAt: new Date(Date.now() + 45_000).toISOString() }, fixture.signer)).rejects.toMatchObject({ status: 403 }); });

  it("returns a signed complete provenance chain and isolates all delegation queries", async () => { const fixture = await setup(); const result = await delegate(fixture); await db().update(v2Tasks).set({ status: "SUCCEEDED", completedAt: new Date().toISOString() }).where(eq(v2Tasks.id, result.created.childTaskId)); await completeAgentDelegation({ accountId: fixture.accountId, delegationId: result.created.delegationId, childAgentId: fixture.childAgentId, outcome: "SUCCEEDED", result: { answer: "done", apiToken: "restricted-canary-value" } }, fixture.signer); const exported = await exportDelegationProvenance({ accountId: fixture.accountId, delegationId: result.created.delegationId }, fixture.signer); expect(exported.bundle.chain).toHaveLength(1); expect(exported.bundle.chain[0]!.result).toMatchObject({ outcome: "SUCCEEDED" }); expect(JSON.stringify(exported)).not.toContain("declared context"); expect(JSON.stringify(exported)).not.toContain("restricted-canary-value"); expect(verifyAuditSignature(await fixture.signer.publicKeyPem(), exported.payloadHash, exported.signature)).toBe(true); const other = await secondAccount(); await expect(getDelegatedContext({ accountId: other, delegationId: result.created.delegationId, childAgentId: fixture.childAgentId })).rejects.toMatchObject({ status: 403 }); await expect(exportDelegationProvenance({ accountId: other, delegationId: result.created.delegationId }, fixture.signer)).rejects.toMatchObject({ status: 404 }); expect(await db().select().from(agentDelegations).where(eq(agentDelegations.accountId, other))).toEqual([]); });

  it("cascade revocation cancels child work, leases, authorities, and budgets", async () => { const fixture = await setup(); const result = await delegate(fixture); const revoked = await revokeAgentDelegation({ accountId: fixture.accountId, delegationId: result.created.delegationId, reason: "parent task revoked" }, fixture.signer); expect(revoked).toMatchObject({ revokedDelegationIds: [result.created.delegationId], cancelledTaskIds: [result.created.childTaskId] }); const [task] = await db().select().from(v2Tasks).where(eq(v2Tasks.id, result.created.childTaskId)); expect(task?.status).toBe("CANCELLED"); const [allocation] = await db().select().from(delegationBudgetAllocations).where(eq(delegationBudgetAllocations.delegationId, result.created.delegationId)); const [budget] = await db().select().from(budgets).where(eq(budgets.id, allocation!.childBudgetId)); expect(budget?.status).toBe("DISABLED"); });
});
