import { generateKeyPairSync, sign } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { budgetReservations, computerControlSessions, executionPlacements, executionProviderDefinitions, purchaseIntents } from "@/lib/db/schema";
import { id } from "@/lib/ids";
import { createApprovalRequest, decideApproval } from "@/lib/v2/approvals";
import { createBudget } from "@/lib/v2/budgets";
import { createComputerControlSession } from "@/lib/v2/computer-control";
import { canonicalHash, type ActionIntent } from "@/lib/v2/contracts";
import { createLocalEd25519Signer } from "@/lib/v2/evidence";
import { redactForEvidence } from "@/lib/v2/evidence/redaction";
import { createWorkloadBootstrap, exchangeWorkloadBootstrap, issueCapabilityLease } from "@/lib/v2/leases";
import { assertNoRawPaymentCredentials, attachPurchaseApproval, beginProtectedHumanCheckout, createPurchaseIntent, FinancialAggregatorRegistry, listPurchaseIntents, listPurchaseReceipts, recordHumanCheckoutOutcome, registerPaymentCredentialReference, reviewHumanCheckout, SimulatedPurchaseExecutor, syncReadOnlyFinancialData } from "@/lib/v2/money";
import { ingestVerifiedEvent, publishEventRoute } from "@/lib/v2/orchestration";
import { activateV2Agent, createV2Agent, issueAgentPassport } from "@/lib/v2/passports";
import { evaluatePolicy, publishRelaySafetyPolicy, registerCapabilityDefinition } from "@/lib/v2/policy";
import { registerRuntimeClient } from "@/lib/v2/runtime-clients";
import { cleanupDatabase, freshDatabase, secondAccount } from "../helpers";

const ownership = { resolveOwnership: async ({ accountId }: { accountId: string }) => ({ name: "resource.account_id", value: accountId, authoritative: true, observedAt: new Date(Date.now() - 100).toISOString(), expiresAt: new Date(Date.now() + 60_000).toISOString(), sourceRevision: "money:1" }) };
const auth = () => ({ sessionId: "ses_money123", method: "password" as const, authenticatedAt: new Date().toISOString() });
const future = (seconds = 45) => new Date(Date.now() + seconds * 1_000).toISOString();

function action(input: { accountId: string; agentId: string; runtimeClientId: string; taskId: string; capability: string; resourceType: string; parameters: Record<string, unknown> }): ActionIntent {
  const material = { capability: { name: input.capability, version: "1.0" }, resource: { type: input.resourceType, attributes: { accountId: input.accountId } }, parameters: input.parameters };
  return { schemaVersion: "relay.action-intent.v2", id: id("act"), accountId: input.accountId, agentId: input.agentId, runtimeClientId: input.runtimeClientId, taskId: input.taskId, ...material, idempotencyKey: crypto.randomUUID(), createdAt: new Date().toISOString(), canonicalHash: canonicalHash(material) };
}

async function setup() {
  const identity = await freshDatabase(); const signer = createLocalEd25519Signer("money-test-key"); const resolver = { publicKeyForKeyId: async (keyId: string) => keyId === signer.keyId ? await signer.publicKeyPem() : undefined }; const runtime = await registerRuntimeClient({ accountId: identity.accountId, actorPrincipalId: identity.principalId, displayName: "Money runtime", selfDeclaredProduct: "custom" }, signer);
  await registerCapabilityDefinition({ name: "computer.checkout.control", version: "1.0", domain: "computer", description: "Protected checkout computer", effectClass: "read", riskClass: "low", resourceType: "computer", inputSchema: {}, outputSchema: {} }, signer); await registerCapabilityDefinition({ name: "money.purchase.request", version: "1.0", domain: "money", description: "Request an exact purchase", effectClass: "financial", riskClass: "critical", resourceType: "purchase", inputSchema: {}, outputSchema: {}, meteringDimensions: ["PURCHASE_AMOUNT"] }, signer); await publishRelaySafetyPolicy({ name: "money-safety", rules: [{ id: "control", effect: "ALLOW", match: { capability: { name: "computer.checkout.control", version: "1.0" } }, reasonCode: "ALLOWED_BY_POLICY" }, { id: "purchase", effect: "REQUIRE_APPROVAL", match: { capability: { name: "money.purchase.request", version: "1.0" } }, reasonCode: "APPROVAL_REQUIRED", approval: { class: "financial", allowedScopes: ["once"] } }] }, signer);
  const agent = await createV2Agent({ accountId: identity.accountId, ownerPrincipalId: identity.principalId, name: "Purchase Agent" }, signer); await issueAgentPassport({ accountId: identity.accountId, agentId: agent.agentId, ownerPrincipalId: identity.principalId, policy: { trustTier: "HIGH_ASSURANCE", capabilityEligibility: [{ name: "computer.checkout.control", version: "1.0" }, { name: "money.purchase.request", version: "1.0" }], policyReferences: ["money-safety"], budgetReferences: [], allowedEnvironments: { providerIds: ["relay-managed"], minimumAssurance: "managed-equivalent" }, dataAccess: [], expiresAt: "2099-01-01T00:00:00.000Z" } }, signer); await activateV2Agent({ accountId: identity.accountId, agentId: agent.agentId, actorPrincipalId: identity.principalId }, signer);
  await publishEventRoute({ accountId: identity.accountId, actorPrincipalId: identity.principalId, name: "purchase", source: "https://money.test/events", eventType: "purchase.requested", agentId: agent.agentId }, signer); const event = await ingestVerifiedEvent({ envelope: { specversion: "1.0", id: crypto.randomUUID(), source: "https://money.test/events", type: "purchase.requested", time: new Date().toISOString(), accountid: identity.accountId, classification: "confidential", correlationid: crypto.randomUUID(), dedupekey: crypto.randomUUID(), schemaversion: "relay.event.v2", signaturestatus: "verified" }, rawBody: new Uint8Array(), headers: {} }, { verify: async () => ({ valid: true }) }, signer); const taskId = event.taskIds[0]!;
  const controlAction = action({ accountId: identity.accountId, agentId: agent.agentId, runtimeClientId: runtime.runtimeClientId, taskId, capability: "computer.checkout.control", resourceType: "computer", parameters: { operation: "observe" } }); await evaluatePolicy({ accountId: identity.accountId, action: controlAction, resourceResolver: ownership }, signer); const pair = generateKeyPairSync("ed25519"); const bootstrap = await createWorkloadBootstrap({ accountId: identity.accountId, agentId: agent.agentId, runtimeClientId: runtime.runtimeClientId, taskId, providerId: "relay-managed", assurance: "managed-equivalent", audience: "relay-managed", publicKeyPem: pair.publicKey.export({ type: "spki", format: "pem" }).toString() }, signer); const workload = await exchangeWorkloadBootstrap({ accountId: identity.accountId, secret: bootstrap.secret, proofSignature: sign(null, Buffer.from(bootstrap.challenge), pair.privateKey).toString("base64url") }, signer); const lease = await issueCapabilityLease({ accountId: identity.accountId, action: controlAction, workloadId: workload.workloadId, workloadIdentityToken: workload.token, audience: "relay-managed", maxCalls: 10 }, signer, resolver);
  const providerDefinitionId = id("pvd"); await db().insert(executionProviderDefinitions).values({ id: providerDefinitionId, providerKey: "money-test", version: "1.0", manifest: {}, manifestHash: canonicalHash({ providerDefinitionId }), signature: "test", signingKeyId: signer.keyId }); const placementId = id("plc"); await db().insert(executionPlacements).values({ id: placementId, accountId: identity.accountId, taskId, actionIntentId: controlAction.id, leaseId: lease.leaseId, providerDefinitionId, status: "RUNNING", requirements: {}, decision: {}, quote: {}, providerSessionId: "checkout-browser" }); const control = await createComputerControlSession({ accountId: identity.accountId, placementId });
  const credential = await registerPaymentCredentialReference({ accountId: identity.accountId, principalId: identity.principalId, provider: "human-browser", credentialHandle: "vlt_paymenttoken1", displayLabel: "Personal Visa ending 4242" }, signer); const budget = await createBudget({ accountId: identity.accountId, actorPrincipalId: identity.principalId, scope: "ACCOUNT", dimension: "PURCHASE_AMOUNT", unit: "currency_unit", currency: "USD", hardLimit: "100" }, signer);
  return { ...identity, signer, resolver, agentId: agent.agentId, runtimeClientId: runtime.runtimeClientId, taskId, controlSessionId: control.controlSessionId, credentialReferenceId: credential.credentialReferenceId, budgetId: budget.budgetId };
}

async function prepare(fixture: Awaited<ReturnType<typeof setup>>, amount = "25.00", suffix = crypto.randomUUID()) {
  const purchase = { merchantId: "merchant-acme", merchantName: "Acme Supplies", currency: "USD", requestedAmount: amount, taxShippingTolerance: "2.00", items: [{ reference: "item-1", description: "Printer paper", quantity: 1, unitAmount: amount }], credentialReferenceId: fixture.credentialReferenceId }; const proposed = action({ accountId: fixture.accountId, agentId: fixture.agentId, runtimeClientId: fixture.runtimeClientId, taskId: fixture.taskId, capability: "money.purchase.request", resourceType: "purchase", parameters: purchase }); const policy = await evaluatePolicy({ accountId: fixture.accountId, action: proposed, resourceResolver: ownership }, fixture.signer); const intent = await createPurchaseIntent({ accountId: fixture.accountId, action: proposed, leafBudgetId: fixture.budgetId, purchase, idempotencyKey: `purchase-${suffix}`, expiresAt: future() }, fixture.signer); const approval = await createApprovalRequest({ accountId: fixture.accountId, action: proposed, policyDecisionId: policy.decisionId, approvalClass: "financial", summary: `Buy from ${purchase.merchantName} for ${amount} USD`, consequence: "The human will commit a real-world payment in protected mode.", displayEvidence: purchase, assignedPrincipalIds: [fixture.principalId], expiresAt: future() }, fixture.signer); await decideApproval({ accountId: fixture.accountId, requestId: approval.requestId, principalId: fixture.principalId, decision: "APPROVE", scope: { kind: "once", actionHash: proposed.canonicalHash }, authenticationEvidence: auth() }, fixture.signer); await attachPurchaseApproval({ accountId: fixture.accountId, purchaseIntentId: intent.purchaseIntentId, approvalRequestId: approval.requestId }); return { purchase, proposed, policy, intent, approval };
}

describe("WO-18 financial domain and controlled purchase intents", () => {
  afterEach(cleanupDatabase);

  it("reserves exact authority, consumes a once approval, fences Agent input, and records a redacted receipt", async () => {
    const fixture = await setup(); const prepared = await prepare(fixture); const checkout = await beginProtectedHumanCheckout({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, controlSessionId: fixture.controlSessionId, expectedFenceToken: 1 }, fixture.signer); expect(checkout.credentialReference).toEqual({ id: fixture.credentialReferenceId, provider: "human-browser", displayLabel: "Personal Visa ending 4242" }); expect(JSON.stringify(checkout)).not.toContain("vlt_paymenttoken1"); const [control] = await db().select().from(computerControlSessions).where(eq(computerControlSessions.id, fixture.controlSessionId)); expect(control).toMatchObject({ controller: "HUMAN", credentialEntryMode: true, activeInputCount: 0, fenceToken: 2 });
    await expect(reviewHumanCheckout({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, permitToken: checkout.permitToken, merchantId: prepared.purchase.merchantId, merchantName: prepared.purchase.merchantName, currency: "USD", finalAmount: "25" }, fixture.signer)).resolves.toEqual({ commitReady: true }); const result = await recordHumanCheckoutOutcome({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, permitToken: checkout.permitToken, outcome: "SUCCEEDED", providerReference: "human-receipt-1", receiptData: { orderId: "A-1", apiToken: "restricted-canary-value" } }, fixture.signer); expect(result).toMatchObject({ status: "COMPLETED", resumeRequired: true }); expect(JSON.stringify(await listPurchaseReceipts(fixture.accountId))).not.toContain("restricted-canary-value"); const [reservation] = await db().select().from(budgetReservations).where(eq(budgetReservations.id, prepared.intent.reservationId)); expect(reservation).toMatchObject({ status: "COMMITTED", actualAmount: "25.000000000" });
  });

  it("invalidates approval and checkout when merchant, currency, or total changes", async () => {
    const fixture = await setup(); const prepared = await prepare(fixture); const checkout = await beginProtectedHumanCheckout({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, controlSessionId: fixture.controlSessionId, expectedFenceToken: 1 }, fixture.signer); await expect(reviewHumanCheckout({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, permitToken: checkout.permitToken, merchantId: prepared.purchase.merchantId, merchantName: prepared.purchase.merchantName, currency: "USD", finalAmount: "25.01" }, fixture.signer)).resolves.toEqual({ commitReady: false, requiresNewIntentAndApproval: true }); const [intent] = await db().select().from(purchaseIntents).where(eq(purchaseIntents.id, prepared.intent.purchaseIntentId)); expect(intent).toMatchObject({ status: "REVIEW_REQUIRED" }); await expect(recordHumanCheckoutOutcome({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, permitToken: checkout.permitToken, outcome: "SUCCEEDED", providerReference: "must-not-run" }, fixture.signer)).rejects.toMatchObject({ status: 403 });
    const substituted = { ...prepared.purchase, merchantId: "attacker", currency: "EUR" }; await expect(createPurchaseIntent({ accountId: fixture.accountId, action: prepared.proposed, leafBudgetId: fixture.budgetId, purchase: substituted, idempotencyKey: "substituted", expiresAt: future() }, fixture.signer)).rejects.toMatchObject({ code: "INVALID_INPUT" });
  });

  it("never retries an ambiguous effect and marks the purchase budget unknown", async () => {
    const fixture = await setup(); const prepared = await prepare(fixture); const checkout = await beginProtectedHumanCheckout({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, controlSessionId: fixture.controlSessionId, expectedFenceToken: 1 }, fixture.signer); await reviewHumanCheckout({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, permitToken: checkout.permitToken, merchantId: prepared.purchase.merchantId, merchantName: prepared.purchase.merchantName, currency: "USD", finalAmount: "25" }, fixture.signer); await expect(recordHumanCheckoutOutcome({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, permitToken: checkout.permitToken, outcome: "EFFECT_UNKNOWN" }, fixture.signer)).resolves.toMatchObject({ status: "EFFECT_UNKNOWN" }); await expect(recordHumanCheckoutOutcome({ accountId: fixture.accountId, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, permitToken: checkout.permitToken, outcome: "SUCCEEDED", providerReference: "retry" }, fixture.signer)).rejects.toMatchObject({ status: 403 }); const [reservation] = await db().select().from(budgetReservations).where(eq(budgetReservations.id, prepared.intent.reservationId)); expect(reservation?.status).toBe("UNKNOWN");
  });

  it("serializes concurrent purchase intents against the shared hard budget", async () => {
    const fixture = await setup(); const build = (suffix: string) => { const purchase = { merchantId: `merchant-${suffix}`, merchantName: `Merchant ${suffix}`, currency: "USD", requestedAmount: "60", taxShippingTolerance: "0", items: [{ reference: suffix, description: "Bounded item", quantity: 1, unitAmount: "60" }], credentialReferenceId: fixture.credentialReferenceId }; return { purchase, proposed: action({ accountId: fixture.accountId, agentId: fixture.agentId, runtimeClientId: fixture.runtimeClientId, taskId: fixture.taskId, capability: "money.purchase.request", resourceType: "purchase", parameters: purchase }) }; }; const first = build("one"); const second = build("two"); const attempts = await Promise.allSettled([createPurchaseIntent({ accountId: fixture.accountId, action: first.proposed, leafBudgetId: fixture.budgetId, purchase: first.purchase, idempotencyKey: "concurrent-one", expiresAt: future() }, fixture.signer), createPurchaseIntent({ accountId: fixture.accountId, action: second.proposed, leafBudgetId: fixture.budgetId, purchase: second.purchase, idempotencyKey: "concurrent-two", expiresAt: future() }, fixture.signer)]); expect(attempts.filter((attempt) => attempt.status === "fulfilled")).toHaveLength(1); expect(attempts.filter((attempt) => attempt.status === "rejected")).toHaveLength(1);
  });

  it("rejects and redacts raw payment data and has no production executor", async () => {
    expect(() => assertNoRawPaymentCredentials({ cardNumber: "4111111111111111", cvv: "123" })).toThrow(/prohibited/); expect(redactForEvidence({ note: "card 4111 1111 1111 1111", routingNumber: "021000021" })).toEqual({ note: "card [REDACTED_PAYMENT_NUMBER]", routingNumber: "[REDACTED]" }); const executor = new SimulatedPurchaseExecutor("test"); expect(executor.execute({ merchantId: "m", merchantName: "Merchant", currency: "USD", finalAmount: "1", outcome: "SUCCEEDED" }).providerReference).toMatch(/^sim_/); vi.stubEnv("NODE_ENV", "production"); expect(() => executor.execute({ merchantId: "m", merchantName: "Merchant", currency: "USD", finalAmount: "1", outcome: "SUCCEEDED" })).toThrow(/test-only/); vi.unstubAllEnvs();
  });

  it("isolates purchase, receipt, and aggregator boundaries by account", async () => {
    const fixture = await setup(); const prepared = await prepare(fixture); const other = await secondAccount(); expect(await listPurchaseIntents(other)).toEqual([]); expect(await listPurchaseReceipts(other)).toEqual([]); await expect(beginProtectedHumanCheckout({ accountId: other, purchaseIntentId: prepared.intent.purchaseIntentId, principalId: fixture.principalId, controlSessionId: fixture.controlSessionId, expectedFenceToken: 1 }, fixture.signer)).rejects.toMatchObject({ status: 403 }); const registry = new FinancialAggregatorRegistry(); await expect(syncReadOnlyFinancialData({ accountId: fixture.accountId, principalId: fixture.principalId, provider: "disabled" }, registry)).rejects.toMatchObject({ status: 503 });
  });
});
