import { generateKeyPairSync, sign } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { computerControlSessions, computerViewerGrants, executionPlacements, executionProviderDefinitions, runnerAssignments, runners, v2Tasks } from "@/lib/db/schema";
import { authorizeHumanComputerInput, beginAgentComputerInput, completeComputerInput, createComputerControlSession, disconnectHumanController, mintComputerViewerGrant, observeComputer, resumeAgentControl, setProtectedCredentialEntry, takeComputerControl } from "@/lib/v2/computer-control";
import { canonicalHash, canonicalJson, type ActionIntent } from "@/lib/v2/contracts";
import { createLocalEd25519Signer } from "@/lib/v2/evidence";
import { createWorkloadBootstrap, exchangeWorkloadBootstrap, issueCapabilityLease } from "@/lib/v2/leases";
import { ingestVerifiedEvent, publishEventRoute } from "@/lib/v2/orchestration";
import { activateV2Agent, createV2Agent, issueAgentPassport } from "@/lib/v2/passports";
import { evaluatePolicy, publishRelaySafetyPolicy, registerCapabilityDefinition } from "@/lib/v2/policy";
import { authorizePrivateGatewayRequest, bindRunnerCredentials, createRunnerAssignment, createRunnerEnrollment, createSignedRunnerUpdate, exchangeRunnerEnrollment, pollRunnerAssignments, registerPrivateGatewayResource, revokeRunner, submitRunnerEvidence } from "@/lib/v2/runners";
import { registerRuntimeClient } from "@/lib/v2/runtime-clients";
import type { ExecutionProviderAdapter } from "@/lib/v2/execution-providers";
import { cleanupDatabase, freshDatabase, secondAccount } from "../helpers";

const digest = (letter: string) => `sha256:${letter.repeat(64)}`;

async function setup() {
  const identity = await freshDatabase(); const signer = createLocalEd25519Signer("runner-control-key"); const resolver = { publicKeyForKeyId: async (keyId: string) => keyId === signer.keyId ? await signer.publicKeyPem() : undefined };
  const runnerKeys = generateKeyPairSync("ed25519"); const enrollment = await createRunnerEnrollment({ accountId: identity.accountId, principalId: identity.principalId, runnerName: "Private runner" }, signer);
  const runner = await exchangeRunnerEnrollment({ accountId: identity.accountId, secret: enrollment.secret, publicKeyPem: runnerKeys.publicKey.export({ type: "spki", format: "pem" }).toString(), proofSignature: sign(null, Buffer.from(enrollment.challenge), runnerKeys.privateKey).toString("base64url"), softwareDigest: digest("a"), configDigest: digest("b") }, signer);
  const runtime = await registerRuntimeClient({ accountId: identity.accountId, actorPrincipalId: identity.principalId, displayName: "Runner runtime", selfDeclaredProduct: "custom" }, signer); const agent = await createV2Agent({ accountId: identity.accountId, ownerPrincipalId: identity.principalId, name: "Runner Agent" }, signer); const capabilityName = "runner.command.execute";
  await registerCapabilityDefinition({ name: capabilityName, version: "1.0", domain: "computer", description: "Run bounded command", effectClass: "read", riskClass: "low", resourceType: "computer", inputSchema: {}, outputSchema: {} }, signer);
  await publishRelaySafetyPolicy({ name: "runner-safety", rules: [{ id: "allow-runner", effect: "ALLOW", match: { capability: { name: capabilityName, version: "1.0" } }, reasonCode: "ALLOWED_BY_POLICY" }] }, signer);
  await issueAgentPassport({ accountId: identity.accountId, agentId: agent.agentId, ownerPrincipalId: identity.principalId, policy: { trustTier: "REGISTERED", capabilityEligibility: [{ name: capabilityName, version: "1.0" }], policyReferences: ["runner-safety"], budgetReferences: [], allowedEnvironments: { providerIds: ["customer-runner"], minimumAssurance: "registered" }, dataAccess: [], expiresAt: "2099-01-01T00:00:00.000Z" } }, signer); await activateV2Agent({ accountId: identity.accountId, agentId: agent.agentId, actorPrincipalId: identity.principalId }, signer);
  await publishEventRoute({ accountId: identity.accountId, actorPrincipalId: identity.principalId, name: "runner", source: "https://runner.test/events", eventType: "runner.work", agentId: agent.agentId }, signer); const event = await ingestVerifiedEvent({ envelope: { specversion: "1.0", id: "runner-work-1", source: "https://runner.test/events", type: "runner.work", time: new Date().toISOString(), accountid: identity.accountId, classification: "internal", correlationid: "runner-work-1", dedupekey: "runner-work-1", schemaversion: "relay.event.v2", signaturestatus: "verified" }, rawBody: new Uint8Array(), headers: {} }, { verify: async () => ({ valid: true }) }, signer); const taskId = event.taskIds[0]!; await db().update(v2Tasks).set({ status: "RUNNING" }).where(eq(v2Tasks.id, taskId));
  const material = { capability: { name: capabilityName, version: "1.0" }, resource: { type: "computer", ids: [runner.runnerId], attributes: { accountId: identity.accountId } }, parameters: { command: "true" } }; const action: ActionIntent = { schemaVersion: "relay.action-intent.v2", id: `act_${crypto.randomUUID().replaceAll("-", "")}`, accountId: identity.accountId, agentId: agent.agentId, runtimeClientId: runtime.runtimeClientId, taskId, ...material, idempotencyKey: crypto.randomUUID(), createdAt: new Date().toISOString(), canonicalHash: canonicalHash(material) };
  await evaluatePolicy({ accountId: identity.accountId, action, resourceResolver: { resolveOwnership: async () => ({ name: "resource.account_id", value: identity.accountId, authoritative: true, observedAt: new Date(Date.now() - 1_000).toISOString(), expiresAt: new Date(Date.now() + 60_000).toISOString(), sourceRevision: "runner" }) } }, signer);
  const workloadKeys = generateKeyPairSync("ed25519"); const bootstrap = await createWorkloadBootstrap({ accountId: identity.accountId, agentId: agent.agentId, runtimeClientId: runtime.runtimeClientId, taskId, runnerId: runner.runnerId, providerId: "customer-runner", assurance: "registered", audience: "customer-runner", publicKeyPem: workloadKeys.publicKey.export({ type: "spki", format: "pem" }).toString() }, signer); const workload = await exchangeWorkloadBootstrap({ accountId: identity.accountId, secret: bootstrap.secret, proofSignature: sign(null, Buffer.from(bootstrap.challenge), workloadKeys.privateKey).toString("base64url") }, signer); const lease = await issueCapabilityLease({ accountId: identity.accountId, action, workloadId: workload.workloadId, workloadIdentityToken: workload.token, audience: "customer-runner", maxCalls: 3 }, signer, resolver);
  const providerDefinitionId = `pvd_${crypto.randomUUID().replaceAll("-", "")}`; const placementId = `plc_${crypto.randomUUID().replaceAll("-", "")}`; const manifestHash = canonicalHash({ provider: "test", id: providerDefinitionId }); await db().insert(executionProviderDefinitions).values({ id: providerDefinitionId, providerKey: "test-control", version: "1.0", manifest: {}, manifestHash, signature: "test", signingKeyId: signer.keyId }); await db().insert(executionPlacements).values({ id: placementId, accountId: identity.accountId, taskId, actionIntentId: action.id, leaseId: lease.leaseId, providerDefinitionId, status: "RUNNING", requirements: {}, decision: {}, quote: {}, providerSessionId: "provider-session-1" });
  return { ...identity, signer, resolver, runnerKeys, runner, taskId, workloadId: workload.workloadId, leaseId: lease.leaseId, placementId };
}

function observationAdapter(): ExecutionProviderAdapter { return { providerKey: "test-control", version: "1.0", health: async () => ({ available: true, warmCapacity: 1, latencyMs: 1, reliabilityBps: 9999, observedAt: new Date().toISOString() }), quote: async () => ({ amount: "0", currency: "USD", validUntil: new Date(Date.now() + 60_000).toISOString() }), prepareExecution: async () => ({ providerSessionId: "provider-session-1", receipt: {} }), control: async () => ({}), observe: async () => ({ liveUrl: "https://provider-secret.example/live" }), collectEvidence: async () => [], collectMeters: async () => [], terminate: async () => ({}), reconcile: async () => ({ status: "ACCEPTED" }) }; }

describe("WO-14 customer runners and private gateway", () => {
  afterEach(cleanupDatabase);
  it("uses one-time proof-of-possession enrollment and does not trust forged attestation", async () => { const identity = await freshDatabase(); const signer = createLocalEd25519Signer(); const keys = generateKeyPairSync("ed25519"); const enrollment = await createRunnerEnrollment({ accountId: identity.accountId, principalId: identity.principalId, runnerName: "Runner" }, signer); const verifier = { verify: vi.fn(async () => ({ verified: false })) }; const request = { accountId: identity.accountId, secret: enrollment.secret, publicKeyPem: keys.publicKey.export({ type: "spki", format: "pem" }).toString(), proofSignature: sign(null, Buffer.from(enrollment.challenge), keys.privateKey).toString("base64url"), softwareDigest: digest("a"), configDigest: digest("b"), attestation: { format: "fake", document: "forged", nonce: "n" } }; await expect(exchangeRunnerEnrollment(request, signer, verifier)).resolves.toMatchObject({ assurance: "registered" }); await expect(exchangeRunnerEnrollment(request, signer, verifier)).rejects.toMatchObject({ status: 401 }); });
  it("polls outbound with a signed certificate and isolates runner assignments by tenant", async () => { const fixture = await setup(); const assignment = await createRunnerAssignment({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, taskId: fixture.taskId, workloadId: fixture.workloadId, leaseId: fixture.leaseId, payload: { command: ["true"] } }, fixture.signer); await expect(pollRunnerAssignments({ accountId: await secondAccount(), runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver)).rejects.toMatchObject({ status: 401 }); await expect(pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: `${fixture.runner.certificate}x` }, fixture.resolver)).rejects.toMatchObject({ status: 401 }); await expect(pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver)).resolves.toEqual([expect.objectContaining({ id: assignment.assignmentId, status: "CLAIMED" })]); });
  it("allows only named assignment-scoped private resources and socket-broker handles", async () => { const fixture = await setup(); const resource = await registerPrivateGatewayResource({ accountId: fixture.accountId, principalId: fixture.principalId, runnerId: fixture.runner.runnerId, name: "private-api", host: "api.internal", port: 443, allowedMethods: ["GET"], allowedPathPrefixes: ["/v1/read"] }); const assignment = await createRunnerAssignment({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, taskId: fixture.taskId, workloadId: fixture.workloadId, leaseId: fixture.leaseId, payload: { command: ["true"], credentialHandles: ["vlt_12345678"], gatewayResourceIds: [resource.resourceId] } }, fixture.signer); await pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver); await expect(authorizePrivateGatewayRequest({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, assignmentId: assignment.assignmentId, resourceId: resource.resourceId, method: "GET", path: "/v1/read/item" })).resolves.toMatchObject({ scheme: "https", host: "api.internal" }); await expect(authorizePrivateGatewayRequest({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, assignmentId: assignment.assignmentId, resourceId: resource.resourceId, method: "POST", path: "/v1/read/item" })).rejects.toMatchObject({ status: 403 }); const broker = { bind: vi.fn(async () => ({ socketBindingId: "socket-1" })) }; await bindRunnerCredentials({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, assignmentId: assignment.assignmentId }, broker); expect(broker.bind).toHaveBeenCalledWith(expect.objectContaining({ handles: ["vlt_12345678"], audience: `runner-socket:${assignment.assignmentId}` })); });
  it("accepts ordered signed runner-reported evidence and rejects stale fences", async () => { const fixture = await setup(); const assignment = await createRunnerAssignment({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, taskId: fixture.taskId, workloadId: fixture.workloadId, leaseId: fixture.leaseId, payload: { command: ["true"] } }, fixture.signer); await pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver); const evidence = { exitCode: 0 }; const material = canonicalJson({ assignmentId: assignment.assignmentId, fenceToken: 1, sequence: 1, evidenceHash: canonicalHash(evidence) }); const signature = sign(null, Buffer.from(material), fixture.runnerKeys.privateKey).toString("base64url"); await expect(submitRunnerEvidence({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate, assignmentId: assignment.assignmentId, fenceToken: 1, sequence: 1, evidence, signature }, fixture.resolver)).resolves.toMatchObject({ accepted: true, source: "runner_reported" }); await expect(submitRunnerEvidence({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate, assignmentId: assignment.assignmentId, fenceToken: 1, sequence: 1, evidence, signature }, fixture.resolver)).rejects.toMatchObject({ status: 409 }); });
  it("revokes runner, assignments, workloads, leases, and future polling", async () => { const fixture = await setup(); await createRunnerAssignment({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, taskId: fixture.taskId, workloadId: fixture.workloadId, leaseId: fixture.leaseId, payload: { command: ["true"] } }, fixture.signer); await expect(createSignedRunnerUpdate({ accountId: fixture.accountId, principalId: fixture.principalId, runnerId: fixture.runner.runnerId, softwareDigest: digest("c"), downloadUrl: "https://updates.relay.example/runner" }, fixture.signer)).resolves.toMatchObject({ signingKeyId: fixture.signer.keyId }); await revokeRunner({ accountId: fixture.accountId, principalId: fixture.principalId, runnerId: fixture.runner.runnerId, reason: "incident" }, fixture.signer); await expect(pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver)).rejects.toMatchObject({ status: 401 }); expect(await db().select({ status: runners.status }).from(runners).where(eq(runners.id, fixture.runner.runnerId))).toEqual([{ status: "REVOKED" }]); expect(await db().select({ status: runnerAssignments.status }).from(runnerAssignments)).toEqual([{ status: "REVOKED" }]); });

  it("makes Agent input and human takeover mutually exclusive under a race", async () => { const fixture = await setup(); const control = await createComputerControlSession({ accountId: fixture.accountId, placementId: fixture.placementId }); const results = await Promise.allSettled([beginAgentComputerInput({ accountId: fixture.accountId, controlSessionId: control.controlSessionId, fenceToken: 1 }), takeComputerControl({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, expectedFenceToken: 1 })]); expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1); const [session] = await db().select().from(computerControlSessions).where(eq(computerControlSessions.id, control.controlSessionId)); if (session!.controller === "AGENT") await completeComputerInput({ accountId: fixture.accountId, controlSessionId: control.controlSessionId, fenceToken: 1 }); else { expect(session).toMatchObject({ controller: "HUMAN", activeInputCount: 0, fenceToken: 2 }); await expect(authorizeHumanComputerInput({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, fenceToken: 2 })).resolves.toBe(true); } });

  it("proxies short-lived viewer grants and suppresses protected credential frames", async () => { const fixture = await setup(); const control = await createComputerControlSession({ accountId: fixture.accountId, placementId: fixture.placementId }); const viewer = await mintComputerViewerGrant({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId }); const relay = { open: vi.fn(async () => ({ streamId: "relay-stream-1", expiresAt: viewer.expiresAt })) }; const observed = await observeComputer({ accountId: fixture.accountId, viewerToken: viewer.token }, observationAdapter(), relay); expect(observed).toMatchObject({ suppressed: false, streamId: "relay-stream-1" }); expect(JSON.stringify(observed)).not.toContain("provider-secret"); const takeover = await takeComputerControl({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, expectedFenceToken: 1 }); await setProtectedCredentialEntry({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, fenceToken: takeover.fenceToken, enabled: true }); await expect(observeComputer({ accountId: fixture.accountId, viewerToken: viewer.token }, observationAdapter(), relay)).resolves.toMatchObject({ suppressed: true }); await db().update(computerViewerGrants).set({ expiresAt: "2000-01-01T00:00:00.000Z" }); await expect(observeComputer({ accountId: fixture.accountId, viewerToken: viewer.token }, observationAdapter(), relay)).rejects.toMatchObject({ status: 401 }); });

  it("resumes only after policy/integrity checks and rotates fences and viewers", async () => { const fixture = await setup(); const control = await createComputerControlSession({ accountId: fixture.accountId, placementId: fixture.placementId }); const viewer = await mintComputerViewerGrant({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId }); const takeover = await takeComputerControl({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, expectedFenceToken: 1 }); const policy = { authorize: vi.fn(async () => true) }; const integrity = { inspect: vi.fn(async () => ({ hash: digest("d"), safe: true })) }; await expect(resumeAgentControl({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, expectedFenceToken: takeover.fenceToken }, policy, integrity)).resolves.toMatchObject({ fenceToken: 3, integrityHash: digest("d") }); expect(policy.authorize).toHaveBeenCalledOnce(); await expect(observeComputer({ accountId: fixture.accountId, viewerToken: viewer.token }, observationAdapter(), { open: async () => ({ streamId: "x", expiresAt: viewer.expiresAt }) })).rejects.toMatchObject({ status: 401 }); await expect(authorizeHumanComputerInput({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, fenceToken: 2 })).rejects.toMatchObject({ status: 409 }); await expect(disconnectHumanController({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, fenceToken: 2 })).resolves.toBe(false); });
});
