import { createHmac, generateKeyPairSync, sign } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { capabilityLeases, communicationMessages, communicationThreads, connectorConnections, connectorOperations, computerControlSessions, computerViewerGrants, executionPlacements, executionProviderDefinitions, runnerAssignments, runners, v2Tasks } from "@/lib/db/schema";
import { CommunicationProviderError, communicationEventSource, createRelayCommunicationEventSink, ingestSlackWebhook, ingestTelegramWebhook, listCommunicationMessages, reconcileCommunication, registerCommunicationConnection, retryRateLimitedCommunication, sendCommunication } from "@/lib/v2/communications";
import { beginConnectorOauth, completeConnectorOauth, ConnectorRegistry, executeConnector, listConnectorConnections, publishConnector, reconcileConnector, revokeConnector, type ConnectorAdapter } from "@/lib/v2/connectors";
import { authorizeHumanComputerInput, beginAgentComputerInput, completeComputerInput, createComputerControlSession, disconnectHumanController, mintComputerViewerGrant, observeComputer, resumeAgentControl, setProtectedCredentialEntry, takeComputerControl } from "@/lib/v2/computer-control";
import { canonicalHash, canonicalJson, type ActionIntent } from "@/lib/v2/contracts";
import { createLocalEd25519Signer } from "@/lib/v2/evidence";
import { createWorkloadBootstrap, exchangeWorkloadBootstrap, issueCapabilityLease } from "@/lib/v2/leases";
import { ingestVerifiedEvent, publishEventRoute } from "@/lib/v2/orchestration";
import { activateV2Agent, createV2Agent, issueAgentPassport } from "@/lib/v2/passports";
import { evaluatePolicy, publishRelaySafetyPolicy, registerCapabilityDefinition } from "@/lib/v2/policy";
import { authorizePrivateGatewayRequest, bindRunnerCredentials, createRunnerAssignment, createRunnerEnrollment, createSignedRunnerUpdate, exchangeRunnerEnrollment, pollRunnerAssignments, registerPrivateGatewayResource, revokeRunner, submitRunnerEvidence } from "@/lib/v2/runners";
import { registerRuntimeClient } from "@/lib/v2/runtime-clients";
import type { ExecutionProviderAdapter } from "@/lib/v2/execution-providers";
import { id } from "@/lib/ids";
import { cleanupDatabase, freshDatabase, secondAccount } from "../helpers";

const digest = (letter: string) => `sha256:${letter.repeat(64)}`;

async function setup() {
  const identity = await freshDatabase(); const signer = createLocalEd25519Signer("runner-control-key"); const resolver = { publicKeyForKeyId: async (keyId: string) => keyId === signer.keyId ? await signer.publicKeyPem() : undefined };
  const runnerKeys = generateKeyPairSync("ed25519"); const enrollment = await createRunnerEnrollment({ accountId: identity.accountId, principalId: identity.principalId, runnerName: "Private runner" }, signer);
  const runner = await exchangeRunnerEnrollment({ accountId: identity.accountId, secret: enrollment.secret, publicKeyPem: runnerKeys.publicKey.export({ type: "spki", format: "pem" }).toString(), proofSignature: sign(null, Buffer.from(enrollment.challenge), runnerKeys.privateKey).toString("base64url"), softwareDigest: digest("a"), configDigest: digest("b") }, signer);
  const runtime = await registerRuntimeClient({ accountId: identity.accountId, actorPrincipalId: identity.principalId, displayName: "Runner runtime", selfDeclaredProduct: "custom" }, signer); const agent = await createV2Agent({ accountId: identity.accountId, ownerPrincipalId: identity.principalId, name: "Runner Agent" }, signer); const capabilityName = "runner.command.execute";
  await registerCapabilityDefinition({ name: capabilityName, version: "1.0", domain: "computer", description: "Run bounded command", effectClass: "read", riskClass: "low", resourceType: "computer", inputSchema: {}, outputSchema: {} }, signer);
  await publishRelaySafetyPolicy({ name: "runner-safety", rules: [{ id: "allow-runner", effect: "ALLOW", match: { capability: { name: capabilityName, version: "1.0" } }, reasonCode: "ALLOWED_BY_POLICY" }] }, signer);
  await issueAgentPassport({ accountId: identity.accountId, agentId: agent.agentId, ownerPrincipalId: identity.principalId, policy: { trustTier: "REGISTERED", capabilityEligibility: [{ name: capabilityName, version: "1.0" }], policyReferences: ["runner-safety"], budgetReferences: [], allowedEnvironments: { providerIds: ["customer-runner"], minimumAssurance: "registered" }, dataAccess: [], expiresAt: "2099-01-01T00:00:00.000Z" } }, signer); await activateV2Agent({ accountId: identity.accountId, agentId: agent.agentId, actorPrincipalId: identity.principalId }, signer);
  await publishEventRoute({ accountId: identity.accountId, actorPrincipalId: identity.principalId, name: "runner", source: "https://runner.test/events", eventType: "runner.work", agentId: agent.agentId }, signer); const event = await ingestVerifiedEvent({ envelope: { specversion: "1.0", id: "runner-work-1", source: "https://runner.test/events", type: "runner.work", time: new Date().toISOString(), accountid: identity.accountId, classification: "internal", correlationid: "runner-work-1", dedupekey: "runner-work-1", schemaversion: "relay.event.v2", signaturestatus: "verified" }, rawBody: new Uint8Array(), headers: {} }, { verify: async () => ({ valid: true }) }, signer); const taskId = event.taskIds[0]!; await db().update(v2Tasks).set({ status: "RUNNING" }).where(eq(v2Tasks.id, taskId));
  const material = { capability: { name: capabilityName, version: "1.0" }, resource: { type: "computer", ids: [runner.runnerId], attributes: { accountId: identity.accountId } }, parameters: { command: "true" } }; const action: ActionIntent = { schemaVersion: "relay.action-intent.v2", id: `act_${crypto.randomUUID().replaceAll("-", "")}`, accountId: identity.accountId, agentId: agent.agentId, runtimeClientId: runtime.runtimeClientId, taskId, ...material, idempotencyKey: crypto.randomUUID(), createdAt: new Date().toISOString(), canonicalHash: canonicalHash(material) };
  await evaluatePolicy({ accountId: identity.accountId, action, resourceResolver: { resolveOwnership: async () => ({ name: "resource.account_id", value: identity.accountId, authoritative: true, observedAt: new Date(Date.now() - 1_000).toISOString(), expiresAt: new Date(Date.now() + 60_000).toISOString(), sourceRevision: "runner" }) } }, signer);
  const workloadKeys = generateKeyPairSync("ed25519"); const bootstrap = await createWorkloadBootstrap({ accountId: identity.accountId, agentId: agent.agentId, runtimeClientId: runtime.runtimeClientId, taskId, runnerId: runner.runnerId, providerId: "customer-runner", assurance: "registered", audience: "customer-runner", publicKeyPem: workloadKeys.publicKey.export({ type: "spki", format: "pem" }).toString() }, signer); const workload = await exchangeWorkloadBootstrap({ accountId: identity.accountId, secret: bootstrap.secret, proofSignature: sign(null, Buffer.from(bootstrap.challenge), workloadKeys.privateKey).toString("base64url") }, signer); const lease = await issueCapabilityLease({ accountId: identity.accountId, action, workloadId: workload.workloadId, workloadIdentityToken: workload.token, audience: "customer-runner", maxCalls: 3 }, signer, resolver);
  const providerDefinitionId = `pvd_${crypto.randomUUID().replaceAll("-", "")}`; const placementId = `plc_${crypto.randomUUID().replaceAll("-", "")}`; const manifestHash = canonicalHash({ provider: "test", id: providerDefinitionId }); await db().insert(executionProviderDefinitions).values({ id: providerDefinitionId, providerKey: "test-control", version: "1.0", manifest: {}, manifestHash, signature: "test", signingKeyId: signer.keyId }); await db().insert(executionPlacements).values({ id: placementId, accountId: identity.accountId, taskId, actionIntentId: action.id, leaseId: lease.leaseId, providerDefinitionId, status: "RUNNING", requirements: {}, decision: {}, quote: {}, providerSessionId: "provider-session-1" });
  return { ...identity, signer, resolver, runnerKeys, runner, agentId: agent.agentId, actionIntentId: action.id, taskId, workloadId: workload.workloadId, leaseId: lease.leaseId, placementId };
}

function observationAdapter(): ExecutionProviderAdapter { return { providerKey: "test-control", version: "1.0", health: async () => ({ available: true, warmCapacity: 1, latencyMs: 1, reliabilityBps: 9999, observedAt: new Date().toISOString() }), quote: async () => ({ amount: "0", currency: "USD", validUntil: new Date(Date.now() + 60_000).toISOString() }), prepareExecution: async () => ({ providerSessionId: "provider-session-1", receipt: {} }), control: async () => ({}), observe: async () => ({ liveUrl: "https://provider-secret.example/live" }), collectEvidence: async () => [], collectMeters: async () => [], terminate: async () => ({}), reconcile: async () => ({ status: "ACCEPTED" }) }; }

describe("WO-14 customer runners and private gateway", () => {
  afterEach(cleanupDatabase);
  it("uses one-time proof-of-possession enrollment and does not trust forged attestation", async () => { const identity = await freshDatabase(); const signer = createLocalEd25519Signer(); const keys = generateKeyPairSync("ed25519"); const enrollment = await createRunnerEnrollment({ accountId: identity.accountId, principalId: identity.principalId, runnerName: "Runner" }, signer); const verifier = { verify: vi.fn(async () => ({ verified: false })) }; const request = { accountId: identity.accountId, secret: enrollment.secret, publicKeyPem: keys.publicKey.export({ type: "spki", format: "pem" }).toString(), proofSignature: sign(null, Buffer.from(enrollment.challenge), keys.privateKey).toString("base64url"), softwareDigest: digest("a"), configDigest: digest("b"), attestation: { format: "fake", document: "forged", nonce: "n" } }; await expect(exchangeRunnerEnrollment(request, signer, verifier)).resolves.toMatchObject({ assurance: "registered" }); await expect(exchangeRunnerEnrollment(request, signer, verifier)).rejects.toMatchObject({ status: 401 }); });
  it("polls outbound with a signed certificate and isolates runner assignments by tenant", async () => { const fixture = await setup(); const assignment = await createRunnerAssignment({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, taskId: fixture.taskId, workloadId: fixture.workloadId, leaseId: fixture.leaseId, payload: { command: ["true"] } }, fixture.signer); await expect(pollRunnerAssignments({ accountId: await secondAccount(), runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver)).rejects.toMatchObject({ status: 401 }); await expect(pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: `${fixture.runner.certificate}x` }, fixture.resolver)).rejects.toMatchObject({ status: 401 }); await expect(pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver)).resolves.toEqual([expect.objectContaining({ id: assignment.assignmentId, status: "CLAIMED" })]); });
  it("allows only named assignment-scoped private resources and socket-broker handles", async () => { const fixture = await setup(); const resource = await registerPrivateGatewayResource({ accountId: fixture.accountId, principalId: fixture.principalId, runnerId: fixture.runner.runnerId, name: "private-api", host: "api.internal", port: 443, allowedMethods: ["GET"], allowedPathPrefixes: ["/v1/read"] }); const assignment = await createRunnerAssignment({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, taskId: fixture.taskId, workloadId: fixture.workloadId, leaseId: fixture.leaseId, payload: { command: ["true"], credentialHandles: ["vlt_12345678"], gatewayResourceIds: [resource.resourceId] } }, fixture.signer); await pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver); await expect(authorizePrivateGatewayRequest({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, assignmentId: assignment.assignmentId, resourceId: resource.resourceId, method: "GET", path: "/v1/read/item" })).resolves.toMatchObject({ scheme: "https", host: "api.internal" }); await expect(authorizePrivateGatewayRequest({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, assignmentId: assignment.assignmentId, resourceId: resource.resourceId, method: "POST", path: "/v1/read/item" })).rejects.toMatchObject({ status: 403 }); const broker = { bind: vi.fn(async () => ({ socketBindingId: "socket-1" })) }; await bindRunnerCredentials({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, assignmentId: assignment.assignmentId }, broker); expect(broker.bind).toHaveBeenCalledWith(expect.objectContaining({ handles: ["vlt_12345678"], audience: `runner-socket:${assignment.assignmentId}` })); });
  it("accepts ordered signed runner-reported evidence and rejects stale fences", async () => { const fixture = await setup(); const assignment = await createRunnerAssignment({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, taskId: fixture.taskId, workloadId: fixture.workloadId, leaseId: fixture.leaseId, payload: { command: ["true"] } }, fixture.signer); await pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver); const evidence = { exitCode: 0 }; const material = canonicalJson({ assignmentId: assignment.assignmentId, fenceToken: 1, sequence: 1, evidenceHash: canonicalHash(evidence) }); const signature = sign(null, Buffer.from(material), fixture.runnerKeys.privateKey).toString("base64url"); await expect(submitRunnerEvidence({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate, assignmentId: assignment.assignmentId, fenceToken: 1, sequence: 1, evidence, signature }, fixture.resolver)).resolves.toMatchObject({ accepted: true, source: "runner_reported" }); await expect(submitRunnerEvidence({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate, assignmentId: assignment.assignmentId, fenceToken: 1, sequence: 1, evidence, signature }, fixture.resolver)).rejects.toMatchObject({ status: 409 }); });
  it("revokes runner, assignments, workloads, leases, and future polling", async () => { const fixture = await setup(); await createRunnerAssignment({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, taskId: fixture.taskId, workloadId: fixture.workloadId, leaseId: fixture.leaseId, payload: { command: ["true"] } }, fixture.signer); await expect(createSignedRunnerUpdate({ accountId: fixture.accountId, principalId: fixture.principalId, runnerId: fixture.runner.runnerId, softwareDigest: digest("c"), downloadUrl: "https://updates.relay.example/runner" }, fixture.signer)).resolves.toMatchObject({ signingKeyId: fixture.signer.keyId }); await revokeRunner({ accountId: fixture.accountId, principalId: fixture.principalId, runnerId: fixture.runner.runnerId, reason: "incident" }, fixture.signer); await expect(pollRunnerAssignments({ accountId: fixture.accountId, runnerId: fixture.runner.runnerId, certificate: fixture.runner.certificate }, fixture.resolver)).rejects.toMatchObject({ status: 401 }); expect(await db().select({ status: runners.status }).from(runners).where(eq(runners.id, fixture.runner.runnerId))).toEqual([{ status: "REVOKED" }]); expect(await db().select({ status: runnerAssignments.status }).from(runnerAssignments)).toEqual([{ status: "REVOKED" }]); });

  it("makes Agent input and human takeover mutually exclusive under a race", async () => { const fixture = await setup(); const control = await createComputerControlSession({ accountId: fixture.accountId, placementId: fixture.placementId }); const results = await Promise.allSettled([beginAgentComputerInput({ accountId: fixture.accountId, controlSessionId: control.controlSessionId, fenceToken: 1 }), takeComputerControl({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, expectedFenceToken: 1 })]); expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1); const [session] = await db().select().from(computerControlSessions).where(eq(computerControlSessions.id, control.controlSessionId)); if (session!.controller === "AGENT") await completeComputerInput({ accountId: fixture.accountId, controlSessionId: control.controlSessionId, fenceToken: 1 }); else { expect(session).toMatchObject({ controller: "HUMAN", activeInputCount: 0, fenceToken: 2 }); await expect(authorizeHumanComputerInput({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, fenceToken: 2 })).resolves.toBe(true); } });

  it("proxies short-lived viewer grants and suppresses protected credential frames", async () => { const fixture = await setup(); const control = await createComputerControlSession({ accountId: fixture.accountId, placementId: fixture.placementId }); const viewer = await mintComputerViewerGrant({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId }); const relay = { open: vi.fn(async () => ({ streamId: "relay-stream-1", expiresAt: viewer.expiresAt })) }; const observed = await observeComputer({ accountId: fixture.accountId, viewerToken: viewer.token }, observationAdapter(), relay); expect(observed).toMatchObject({ suppressed: false, streamId: "relay-stream-1" }); expect(JSON.stringify(observed)).not.toContain("provider-secret"); const takeover = await takeComputerControl({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, expectedFenceToken: 1 }); await setProtectedCredentialEntry({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, fenceToken: takeover.fenceToken, enabled: true }); await expect(observeComputer({ accountId: fixture.accountId, viewerToken: viewer.token }, observationAdapter(), relay)).resolves.toMatchObject({ suppressed: true }); await db().update(computerViewerGrants).set({ expiresAt: "2000-01-01T00:00:00.000Z" }); await expect(observeComputer({ accountId: fixture.accountId, viewerToken: viewer.token }, observationAdapter(), relay)).rejects.toMatchObject({ status: 401 }); });

  it("resumes only after policy/integrity checks and rotates fences and viewers", async () => { const fixture = await setup(); const control = await createComputerControlSession({ accountId: fixture.accountId, placementId: fixture.placementId }); const viewer = await mintComputerViewerGrant({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId }); const takeover = await takeComputerControl({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, expectedFenceToken: 1 }); const policy = { authorize: vi.fn(async () => true) }; const integrity = { inspect: vi.fn(async () => ({ hash: digest("d"), safe: true })) }; await expect(resumeAgentControl({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, expectedFenceToken: takeover.fenceToken }, policy, integrity)).resolves.toMatchObject({ fenceToken: 3, integrityHash: digest("d") }); expect(policy.authorize).toHaveBeenCalledOnce(); await expect(observeComputer({ accountId: fixture.accountId, viewerToken: viewer.token }, observationAdapter(), { open: async () => ({ streamId: "x", expiresAt: viewer.expiresAt }) })).rejects.toMatchObject({ status: 401 }); await expect(authorizeHumanComputerInput({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, fenceToken: 2 })).rejects.toMatchObject({ status: 409 }); await expect(disconnectHumanController({ accountId: fixture.accountId, principalId: fixture.principalId, controlSessionId: control.controlSessionId, fenceToken: 2 })).resolves.toBe(false); });
});

describe("WO-17 Google Drive and Linear connectors", () => {
  afterEach(cleanupDatabase);

  function googleAdapter(accessible: { value: string[] }, effect: { value: "SUCCEEDED" | "EFFECT_UNKNOWN" } = { value: "SUCCEEDED" }): ConnectorAdapter {
    return { provider: "GOOGLE_DRIVE", version: "1.0", inspectAccess: async () => ({ scopes: ["openid", "email", "https://www.googleapis.com/auth/drive.file"], accessibleResourceIds: accessible.value, writableResourceIds: accessible.value }), prepare: async () => ({ providerResourceId: "drive-generated-1" }), execute: async () => effect.value === "SUCCEEDED" ? ({ state: "SUCCEEDED", providerResourceId: "drive-generated-1", receipt: { providerRequestId: "g-1" } }) : ({ state: "EFFECT_UNKNOWN", receipt: { errorClass: "TIMEOUT" } }), reconcile: async () => ({ state: "SUCCEEDED", providerResourceId: "drive-generated-1", receipt: { reconciledByGet: true } }) };
  }

  it("uses one-time tenant-bound OAuth state and stores only broker handles with visible scopes", async () => {
    const fixture = await setup(); const accessible = { value: ["folder-1"] }; const adapter = googleAdapter(accessible); const manifest = { schemaVersion: "relay.connector.v1" as const, provider: "GOOGLE_DRIVE" as const, version: "1.0", oauthScopes: ["openid", "email", "https://www.googleapis.com/auth/drive.file"], capabilities: ["connectors.drive.file.search", "connectors.drive.file.read", "connectors.drive.file.create", "connectors.drive.file.update"], networkHosts: ["www.googleapis.com"], secretAccess: "credential_handle" as const, supportsReconciliation: true }; await publishConnector(manifest, adapter, fixture.signer);
    const broker = { createPkce: vi.fn(async () => ({ authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth", codeVerifierHandle: "vlt_verifier123" })), exchange: vi.fn(async () => ({ credentialHandle: "vlt_google1234", externalAccountId: "owner@example.com", displayName: "Owner Drive", scopes: manifest.oauthScopes, accessibleResourceIds: accessible.value, writableResourceIds: accessible.value })), revoke: vi.fn(async () => undefined) };
    const flow = await beginConnectorOauth({ accountId: fixture.accountId, principalId: fixture.principalId, provider: "GOOGLE_DRIVE", redirectUri: "https://relay.example/oauth/google", restrictions: { rootFolderIds: ["folder-1"], fileIds: [] } }, broker); const connected = await completeConnectorOauth({ accountId: fixture.accountId, principalId: fixture.principalId, provider: "GOOGLE_DRIVE", state: flow.state, code: "oauth-code" }, broker);
    await expect(completeConnectorOauth({ accountId: fixture.accountId, principalId: fixture.principalId, provider: "GOOGLE_DRIVE", state: flow.state, code: "oauth-code" }, broker)).rejects.toMatchObject({ status: 401 }); const listed = await listConnectorConnections(fixture.accountId); expect(listed).toEqual([expect.objectContaining({ id: connected.connectionId, scopes: manifest.oauthScopes, restrictions: { rootFolderIds: ["folder-1"], fileIds: [] } })]); expect(await listConnectorConnections(await secondAccount())).toEqual([]);
    const [stored] = await db().select().from(connectorConnections).where(eq(connectorConnections.id, connected.connectionId)); expect(stored).toMatchObject({ credentialHandle: "vlt_google1234" }); expect(JSON.stringify(stored)).not.toContain("oauth-code");
  });

  it("enforces selected roots and lease hashes, reconciles writes, and detects permission drift", async () => {
    const fixture = await setup(); const accessible = { value: ["folder-1"] }; const effect = { value: "EFFECT_UNKNOWN" as "SUCCEEDED" | "EFFECT_UNKNOWN" }; const adapter = googleAdapter(accessible, effect); const registry = new ConnectorRegistry(fixture.resolver); registry.register(adapter); const manifest = { schemaVersion: "relay.connector.v1" as const, provider: "GOOGLE_DRIVE" as const, version: "1.0", oauthScopes: ["openid", "email", "https://www.googleapis.com/auth/drive.file"], capabilities: ["connectors.drive.file.search", "connectors.drive.file.read", "connectors.drive.file.create", "connectors.drive.file.update"], networkHosts: ["www.googleapis.com"], secretAccess: "credential_handle" as const, supportsReconciliation: true }; const definition = await publishConnector(manifest, adapter, fixture.signer); const connectionId = id("cnx"); const snapshot = { scopes: manifest.oauthScopes, accessibleResourceIds: accessible.value }; await db().insert(connectorConnections).values({ id: connectionId, accountId: fixture.accountId, definitionId: definition.definitionId, provider: "GOOGLE_DRIVE", externalAccountId: "owner", displayName: "Drive", scopes: manifest.oauthScopes, restrictions: { rootFolderIds: ["folder-1"], fileIds: [] }, credentialHandle: "vlt_google1234", permissionSnapshot: snapshot, permissionSnapshotHash: canonicalHash(snapshot), lastVerifiedAt: new Date().toISOString() });
    const capability = "connectors.drive.file.create"; const parameters = { containerId: "folder-1", name: "report.txt" }; const [lease] = await db().select().from(capabilityLeases).where(eq(capabilityLeases.id, fixture.leaseId)); const claims = lease!.claims as Record<string, unknown>; await db().update(capabilityLeases).set({ claims: { ...claims, capability: { name: capability, version: "1.0" }, actionHash: canonicalHash({ capability: { name: capability, version: "1.0" }, resource: claims.resource, parameters }) } }).where(eq(capabilityLeases.id, fixture.leaseId)); const request = { accountId: fixture.accountId, connectionId, taskId: fixture.taskId, actionIntentId: fixture.actionIntentId, leaseId: fixture.leaseId, capability, parameters, idempotencyKey: "drive-create-1" };
    const result = await executeConnector(request, registry); expect(result).toMatchObject({ status: "EFFECT_UNKNOWN", providerResourceId: "drive-generated-1" }); await expect(executeConnector(request, registry)).resolves.toMatchObject({ operationId: result.operationId, idempotentReplay: true }); await expect(reconcileConnector({ accountId: fixture.accountId, operationId: result.operationId }, registry)).resolves.toMatchObject({ status: "SUCCEEDED", providerResourceId: "drive-generated-1" });
    const otherAccountId = await secondAccount(); await expect(executeConnector({ ...request, accountId: otherAccountId, idempotencyKey: "cross-tenant" }, registry)).rejects.toMatchObject({ status: 404 }); expect(await db().select().from(connectorOperations).where(eq(connectorOperations.accountId, otherAccountId))).toEqual([]);
    const outside = { ...request, parameters: { ...parameters, containerId: "folder-2" }, idempotencyKey: "outside-root" }; await db().update(capabilityLeases).set({ claims: { ...claims, capability: { name: capability, version: "1.0" }, actionHash: canonicalHash({ capability: { name: capability, version: "1.0" }, resource: claims.resource, parameters: outside.parameters }) } }).where(eq(capabilityLeases.id, fixture.leaseId)); await expect(executeConnector(outside, registry)).rejects.toMatchObject({ status: 403 });
    accessible.value = []; const drift = { ...request, idempotencyKey: "drift-1" }; await db().update(capabilityLeases).set({ claims: { ...claims, capability: { name: capability, version: "1.0" }, actionHash: canonicalHash({ capability: { name: capability, version: "1.0" }, resource: claims.resource, parameters }) } }).where(eq(capabilityLeases.id, fixture.leaseId)); await expect(executeConnector(drift, registry)).rejects.toMatchObject({ status: 403 }); const [connection] = await db().select().from(connectorConnections).where(eq(connectorConnections.id, connectionId)); expect(connection).toMatchObject({ status: "ERROR" });
  });

  it("revokes provider credentials and fails closed before future connector effects", async () => {
    const fixture = await setup(); const adapter = googleAdapter({ value: ["folder-1"] }); const manifest = { schemaVersion: "relay.connector.v1" as const, provider: "GOOGLE_DRIVE" as const, version: "1.0", oauthScopes: ["openid", "email", "https://www.googleapis.com/auth/drive.file"], capabilities: ["connectors.drive.file.search", "connectors.drive.file.read", "connectors.drive.file.create", "connectors.drive.file.update"], networkHosts: ["www.googleapis.com"], secretAccess: "credential_handle" as const, supportsReconciliation: true }; const definition = await publishConnector(manifest, adapter, fixture.signer); const connectionId = id("cnx"); const snapshot = { scopes: manifest.oauthScopes, accessibleResourceIds: ["folder-1"] }; await db().insert(connectorConnections).values({ id: connectionId, accountId: fixture.accountId, definitionId: definition.definitionId, provider: "GOOGLE_DRIVE", externalAccountId: "owner", displayName: "Drive", scopes: manifest.oauthScopes, restrictions: { rootFolderIds: ["folder-1"], fileIds: [] }, credentialHandle: "vlt_google1234", permissionSnapshot: snapshot, permissionSnapshotHash: canonicalHash(snapshot), lastVerifiedAt: new Date().toISOString() }); const broker = { createPkce: vi.fn(), exchange: vi.fn(), revoke: vi.fn(async () => undefined) }; await revokeConnector({ accountId: fixture.accountId, principalId: fixture.principalId, connectionId }, broker); expect(broker.revoke).toHaveBeenCalledWith({ accountId: fixture.accountId, credentialHandle: "vlt_google1234" }); const [connection] = await db().select().from(connectorConnections).where(eq(connectorConnections.id, connectionId)); expect(connection).toMatchObject({ status: "DISCONNECTED" });
  });

  it("restricts Linear writes to selected teams and the qualified issue fields", async () => {
    const fixture = await setup(); const adapter: ConnectorAdapter = { provider: "LINEAR", version: "1.0", inspectAccess: async () => ({ scopes: ["read", "write"], accessibleResourceIds: ["team-1"], writableResourceIds: ["team-1"] }), execute: async () => ({ state: "SUCCEEDED", providerResourceId: "issue-1", receipt: { identifier: "REL-1", accessToken: "canary-provider-secret" } }), reconcile: async () => ({ state: "SUCCEEDED", providerResourceId: "issue-1", receipt: { relayReference: "linear-create-1" } }) }; const registry = new ConnectorRegistry(fixture.resolver); registry.register(adapter); const manifest = { schemaVersion: "relay.connector.v1" as const, provider: "LINEAR" as const, version: "1.0", oauthScopes: ["read", "write"], capabilities: ["connectors.linear.issue.search", "connectors.linear.issue.read", "connectors.linear.issue.create", "connectors.linear.issue.update"], networkHosts: ["api.linear.app"], secretAccess: "credential_handle" as const, supportsReconciliation: true }; const definition = await publishConnector(manifest, adapter, fixture.signer); const connectionId = id("cnx"); const snapshot = { scopes: manifest.oauthScopes, accessibleResourceIds: ["team-1"], writableResourceIds: ["team-1"] }; await db().insert(connectorConnections).values({ id: connectionId, accountId: fixture.accountId, definitionId: definition.definitionId, provider: "LINEAR", externalAccountId: "workspace-1", displayName: "Linear", scopes: manifest.oauthScopes, restrictions: { teamIds: ["team-1"] }, credentialHandle: "vlt_linear1234", permissionSnapshot: snapshot, permissionSnapshotHash: canonicalHash(snapshot), lastVerifiedAt: new Date().toISOString() });
    const capability = "connectors.linear.issue.create"; const parameters = { teamId: "team-1", title: "Investigate", description: "Bounded issue" }; const [lease] = await db().select().from(capabilityLeases).where(eq(capabilityLeases.id, fixture.leaseId)); const claims = lease!.claims as Record<string, unknown>; const bind = async (next: Record<string, unknown>) => await db().update(capabilityLeases).set({ claims: { ...claims, capability: { name: capability, version: "1.0" }, actionHash: canonicalHash({ capability: { name: capability, version: "1.0" }, resource: claims.resource, parameters: next }) } }).where(eq(capabilityLeases.id, fixture.leaseId)); await bind(parameters); const request = { accountId: fixture.accountId, connectionId, taskId: fixture.taskId, actionIntentId: fixture.actionIntentId, leaseId: fixture.leaseId, capability, parameters, idempotencyKey: "linear-create-1" }; const result = await executeConnector(request, registry); expect(result).toMatchObject({ status: "SUCCEEDED", providerResourceId: "issue-1" }); const [operation] = await db().select().from(connectorOperations).where(eq(connectorOperations.id, result.operationId)); expect(JSON.stringify(operation!.receipt)).not.toContain("canary-provider-secret");
    const wrongTeam = { ...parameters, teamId: "team-2" }; await bind(wrongTeam); await expect(executeConnector({ ...request, parameters: wrongTeam, idempotencyKey: "linear-wrong-team" }, registry)).rejects.toMatchObject({ status: 403 }); const forbiddenField = { ...parameters, stateId: "state-done" }; await bind(forbiddenField); await expect(executeConnector({ ...request, parameters: forbiddenField, idempotencyKey: "linear-state-change" }, registry)).rejects.toMatchObject({ status: 403 });
  });
});

describe("WO-16 Slack and Telegram communications", () => {
  afterEach(cleanupDatabase);
  it("verifies Slack signatures, rejects replay-window abuse, wakes one task, and suppresses bot echoes", async () => {
    const fixture = await setup(); const secret = "slack-signing-secret";
    const connection = await registerCommunicationConnection({ accountId: fixture.accountId, principalId: fixture.principalId, provider: "SLACK", externalAccountId: "T-RELAY", ownedIdentityId: "B-RELAY", credentialHandle: "vlt_slacktoken1", webhookSecretHandle: "vlt_slacksecret1" });
    await publishEventRoute({ accountId: fixture.accountId, actorPrincipalId: fixture.principalId, name: "slack-messages", source: communicationEventSource("SLACK", connection.connectionId), eventType: "communication.message.received", agentId: fixture.agentId }, fixture.signer);
    const secrets = { resolve: vi.fn(async (_accountId: string, handle: string) => handle === "vlt_slacksecret1" ? secret : "token") }; const sink = createRelayCommunicationEventSink(fixture.signer); const timestamp = String(Math.floor(Date.now() / 1_000));
    const body = JSON.stringify({ event_id: "Ev-1", team_id: "T-RELAY", event: { type: "message", user: "U-1", channel: "C-1", ts: "171.1", text: "hello" } }); const signature = `v0=${createHmac("sha256", secret).update(`v0:${timestamp}:${body}`).digest("hex")}`;
    const accepted = await ingestSlackWebhook({ rawBody: Buffer.from(body), timestamp, signature }, secrets, sink); expect(accepted.taskIds).toHaveLength(1);
    await expect(ingestSlackWebhook({ rawBody: Buffer.from(body), timestamp, signature: `${signature}0` }, secrets, sink)).rejects.toMatchObject({ status: 401 });
    await expect(ingestSlackWebhook({ rawBody: Buffer.from(body), timestamp: String(Number(timestamp) - 301), signature }, secrets, sink)).rejects.toMatchObject({ status: 401 });
    await expect(ingestSlackWebhook({ rawBody: Buffer.from(body), timestamp, signature }, secrets, sink)).resolves.toMatchObject({ duplicate: true, taskIds: [] });
    const echoBody = JSON.stringify({ event_id: "Ev-2", team_id: "T-RELAY", event: { type: "message", bot_id: "B-RELAY", channel: "C-1", ts: "171.2", text: "echo" } }); const echoSignature = `v0=${createHmac("sha256", secret).update(`v0:${timestamp}:${echoBody}`).digest("hex")}`;
    await expect(ingestSlackWebhook({ rawBody: Buffer.from(echoBody), timestamp, signature: echoSignature }, secrets, sink)).resolves.toMatchObject({ duplicate: true, taskIds: [] });
    const [echo] = await db().select().from(communicationMessages).where(eq(communicationMessages.providerEventId, "Ev-2")); expect(echo).toMatchObject({ status: "SUPPRESSED" });
    expect(await listCommunicationMessages(await secondAccount(), echo!.threadId)).toEqual([]);
  });

  it("verifies Telegram webhook tokens, deduplicates updates, and classifies attachment metadata", async () => {
    const fixture = await setup(); await registerCommunicationConnection({ accountId: fixture.accountId, principalId: fixture.principalId, provider: "TELEGRAM", externalAccountId: "bot-1", ownedIdentityId: "999", credentialHandle: "vlt_telegramtoken", webhookSecretHandle: "vlt_telegramsecret" });
    const secrets = { resolve: async () => "telegram-secret" }; const sink = { publish: vi.fn(async () => ({ taskIds: [fixture.taskId] })) }; const rawBody = Buffer.from(JSON.stringify({ update_id: 42, message: { message_id: 9, from: { id: 123 }, chat: { id: 456 }, caption: "invoice", document: { file_id: "file-1", file_name: "invoice.pdf", mime_type: "application/pdf", file_size: 1024 } } }));
    await expect(ingestTelegramWebhook({ externalAccountId: "bot-1", rawBody, secretToken: "bad" }, secrets, sink)).rejects.toMatchObject({ status: 401 });
    await expect(ingestTelegramWebhook({ externalAccountId: "bot-1", rawBody, secretToken: "telegram-secret" }, secrets, sink)).resolves.toMatchObject({ taskIds: [fixture.taskId] });
    await expect(ingestTelegramWebhook({ externalAccountId: "bot-1", rawBody, secretToken: "telegram-secret" }, secrets, sink)).resolves.toMatchObject({ duplicate: true });
    expect(sink.publish).toHaveBeenCalledOnce(); const [message] = await db().select().from(communicationMessages).where(eq(communicationMessages.providerEventId, "42")); expect(message).toMatchObject({ classification: "confidential", status: "ROUTED" });
  });

  it("requires approval for a new recipient, sends once, isolates tenants, and reconciles ambiguity", async () => {
    const fixture = await setup(); const connection = await registerCommunicationConnection({ accountId: fixture.accountId, principalId: fixture.principalId, provider: "SLACK", externalAccountId: "T-SEND", ownedIdentityId: "B-SEND", credentialHandle: "vlt_sendtoken1", webhookSecretHandle: "vlt_sendsecret1" }); const threadId = id("cmt");
    await db().insert(communicationThreads).values({ id: threadId, accountId: fixture.accountId, connectionId: connection.connectionId, externalConversationId: "C-SEND", externalThreadId: "", recipientId: "U-NEW", knownRecipient: false });
    const [lease] = await db().select().from(capabilityLeases).where(eq(capabilityLeases.id, fixture.leaseId)); const baseClaims = lease!.claims as Record<string, unknown>; const text = "Approved hello"; const material = { capability: baseClaims.capability, resource: baseClaims.resource, parameters: { threadId, text } };
    await db().update(capabilityLeases).set({ claims: { ...baseClaims, actionHash: canonicalHash(material) } }).where(eq(capabilityLeases.id, fixture.leaseId)); const secrets = { resolve: async () => "provider-token" }; const sender = { send: vi.fn(async () => ({ providerMessageId: "171.99", state: "SENT" as const, receipt: { accepted: true } })), reconcile: vi.fn(async () => ({ providerMessageId: "171.100", state: "DELIVERED" as const })) }; const request = { accountId: fixture.accountId, connectionId: connection.connectionId, threadId, taskId: fixture.taskId, actionIntentId: fixture.actionIntentId, leaseId: fixture.leaseId, text, idempotencyKey: "send-once-1" };
    await expect(sendCommunication(request, secrets, sender)).rejects.toMatchObject({ status: 403 }); expect(await db().select().from(communicationMessages)).toEqual([]);
    await db().update(capabilityLeases).set({ claims: { ...baseClaims, actionHash: canonicalHash(material), approvalDecisionId: id("apd") } }).where(eq(capabilityLeases.id, fixture.leaseId));
    const sent = await sendCommunication(request, secrets, sender); await expect(sendCommunication(request, secrets, sender)).resolves.toMatchObject({ messageId: sent.messageId, idempotentReplay: true }); expect(sender.send).toHaveBeenCalledOnce();
    const [stored] = await db().select().from(communicationMessages).where(eq(communicationMessages.id, sent.messageId)); expect(stored).toMatchObject({ providerMessageId: "171.99", status: "SENT", attemptCount: 1 }); expect(stored!.providerReceipt).toMatchObject({ finalState: "SENT", accepted: true });
    const otherAccountId = await secondAccount(); expect(await listCommunicationMessages(otherAccountId, threadId)).toEqual([]); await expect(sendCommunication({ ...request, accountId: otherAccountId, idempotencyKey: "cross-tenant" }, secrets, sender)).rejects.toMatchObject({ status: 403 });
    const rateText = "Rate limited"; const rateMaterial = { capability: baseClaims.capability, resource: baseClaims.resource, parameters: { threadId, text: rateText } }; await db().update(capabilityLeases).set({ claims: { ...baseClaims, actionHash: canonicalHash(rateMaterial), approvalDecisionId: id("apd") } }).where(eq(capabilityLeases.id, fixture.leaseId));
    sender.send.mockRejectedValueOnce(new CommunicationProviderError("slow down", "RATE_LIMIT", 1_000)); const rateRequest = { ...request, text: rateText, idempotencyKey: "send-rate-1" }; await expect(sendCommunication(rateRequest, secrets, sender)).rejects.toMatchObject({ status: 502 }); const [rateMessage] = await db().select().from(communicationMessages).where(eq(communicationMessages.idempotencyKey, rateRequest.idempotencyKey)); await db().update(communicationMessages).set({ retryAfter: "2000-01-01T00:00:00.000Z" }).where(eq(communicationMessages.id, rateMessage!.id)); sender.send.mockResolvedValueOnce({ providerMessageId: "171.101", state: "SENT", receipt: { accepted: true } });
    const retries = await Promise.allSettled([retryRateLimitedCommunication({ accountId: fixture.accountId, messageId: rateMessage!.id }, secrets, sender), retryRateLimitedCommunication({ accountId: fixture.accountId, messageId: rateMessage!.id }, secrets, sender)]); expect(retries.filter((result) => result.status === "fulfilled")).toHaveLength(1); const [retried] = await db().select().from(communicationMessages).where(eq(communicationMessages.id, rateMessage!.id)); expect(retried).toMatchObject({ status: "SENT", attemptCount: 2, providerMessageId: "171.101" });
    const ambiguousText = "Ambiguous"; const ambiguousMaterial = { capability: baseClaims.capability, resource: baseClaims.resource, parameters: { threadId, text: ambiguousText } }; await db().update(capabilityLeases).set({ claims: { ...baseClaims, actionHash: canonicalHash(ambiguousMaterial), approvalDecisionId: id("apd") } }).where(eq(capabilityLeases.id, fixture.leaseId));
    sender.send.mockRejectedValueOnce(new CommunicationProviderError("timeout", "TIMEOUT")); const ambiguousRequest = { ...request, text: ambiguousText, idempotencyKey: "send-ambiguous-1" }; await expect(sendCommunication(ambiguousRequest, secrets, sender)).rejects.toMatchObject({ status: 502 }); const [ambiguous] = await db().select().from(communicationMessages).where(eq(communicationMessages.idempotencyKey, ambiguousRequest.idempotencyKey)); expect(ambiguous).toMatchObject({ status: "EFFECT_UNKNOWN" });
    await expect(retryRateLimitedCommunication({ accountId: fixture.accountId, messageId: ambiguous!.id }, secrets, sender)).rejects.toMatchObject({ status: 409 }); await expect(reconcileCommunication({ accountId: fixture.accountId, messageId: ambiguous!.id }, secrets, sender)).resolves.toMatchObject({ status: "DELIVERED", providerMessageId: "171.100" });
  });
});
