import { randomBytes } from "node:crypto";
import { and, eq, gt, inArray, isNull, sql } from "drizzle-orm";
import { hashSecret } from "@/lib/crypto";
import { db, withTransaction } from "@/lib/db";
import { capabilityLeases, computerControlEvents, computerControlSessions, computerViewerGrants, executionPlacements } from "@/lib/db/schema";
import { RelayError } from "@/lib/errors";
import { id, now } from "@/lib/ids";
import { requireMembership } from "@/lib/v2/identity";
import type { ExecutionProviderAdapter } from "@/lib/v2/execution-providers";

export interface ResumePolicyCheck { authorize(input: { accountId: string; taskId: string; leaseId: string; controlSessionId: string }): Promise<boolean> }
export interface ResumeIntegrityCheck { inspect(input: { accountId: string; taskId: string; leaseId: string; providerSessionId: string }): Promise<{ hash: string; safe: boolean }> }
export interface ObservationRelay { open(input: { accountId: string; controlSessionId: string; upstream: Awaited<ReturnType<ExecutionProviderAdapter["observe"]>>; expiresAt: string }): Promise<{ streamId: string; expiresAt: string }> }

export async function createComputerControlSession(input: { accountId: string; placementId: string; expiresAt?: string }) {
  const timestamp = now(); const [placement] = await db().select().from(executionPlacements).innerJoin(capabilityLeases, and(eq(capabilityLeases.id, executionPlacements.leaseId), eq(capabilityLeases.accountId, executionPlacements.accountId))).where(and(eq(executionPlacements.accountId, input.accountId), eq(executionPlacements.id, input.placementId), eq(executionPlacements.status, "RUNNING"), isNull(capabilityLeases.revokedAt), eq(capabilityLeases.status, "ACTIVE"), gt(capabilityLeases.expiresAt, timestamp))).limit(1);
  if (!placement?.execution_placements.providerSessionId) throw new RelayError("CAPABILITY_DENIED", "A running account-bound placement and lease are required.", undefined, 403);
  const row = placement.execution_placements; const providerSessionId = row.providerSessionId!; const controlSessionId = id("ccs"); const expiresAt = new Date(Math.min(input.expiresAt ? Date.parse(input.expiresAt) : Date.now() + 3600_000, Date.parse(placement.capability_leases.expiresAt))).toISOString();
  await db().insert(computerControlSessions).values({ id: controlSessionId, accountId: input.accountId, placementId: row.id, taskId: row.taskId, leaseId: row.leaseId, providerSessionId, expiresAt }); return { controlSessionId, fenceToken: 1, expiresAt };
}

export async function mintComputerViewerGrant(input: { accountId: string; principalId: string; controlSessionId: string; ttlSeconds?: number }) {
  await requireMembership({ accountId: input.accountId, principalId: input.principalId }); const [session] = await db().select().from(computerControlSessions).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), inArray(computerControlSessions.controller, ["AGENT", "PAUSED", "HUMAN"]), gt(computerControlSessions.expiresAt, now()))).limit(1); if (!session) throw new RelayError("CAPABILITY_DENIED", "Computer session is unavailable.", undefined, 404);
  const token = `view_${randomBytes(32).toString("base64url")}`; const expiresAt = new Date(Math.min(Date.now() + Math.min(Math.max(input.ttlSeconds ?? 60, 10), 120) * 1_000, Date.parse(session.expiresAt))).toISOString(); await db().insert(computerViewerGrants).values({ id: id("cvg"), accountId: input.accountId, controlSessionId: session.id, principalId: input.principalId, tokenHash: hashSecret(token), viewerEpoch: session.viewerEpoch, expiresAt }); return { token, expiresAt };
}

export async function observeComputer(input: { accountId: string; viewerToken: string }, adapter: ExecutionProviderAdapter, relay: ObservationRelay) {
  const [binding] = await db().select({ grant: computerViewerGrants, session: computerControlSessions }).from(computerViewerGrants).innerJoin(computerControlSessions, and(eq(computerControlSessions.id, computerViewerGrants.controlSessionId), eq(computerControlSessions.accountId, computerViewerGrants.accountId))).where(and(eq(computerViewerGrants.accountId, input.accountId), eq(computerViewerGrants.tokenHash, hashSecret(input.viewerToken)), isNull(computerViewerGrants.revokedAt), gt(computerViewerGrants.expiresAt, now()), inArray(computerControlSessions.controller, ["AGENT", "PAUSED", "HUMAN"]), gt(computerControlSessions.expiresAt, now()))).limit(1);
  if (!binding || binding.grant.viewerEpoch !== binding.session.viewerEpoch) throw new RelayError("INVALID_CREDENTIAL", "Viewer grant is invalid or expired.", undefined, 401); if (binding.session.credentialEntryMode) return { suppressed: true as const, reason: "PROTECTED_CREDENTIAL_ENTRY" };
  const upstream = await adapter.observe({ accountId: input.accountId, taskId: binding.session.taskId, leaseId: binding.session.leaseId, providerSessionId: binding.session.providerSessionId }); return { suppressed: false as const, ...await relay.open({ accountId: input.accountId, controlSessionId: binding.session.id, upstream, expiresAt: binding.grant.expiresAt }) };
}

export async function beginAgentComputerInput(input: { accountId: string; controlSessionId: string; fenceToken: number }) { const [session] = await db().update(computerControlSessions).set({ activeInputCount: sql`${computerControlSessions.activeInputCount} + 1`, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), eq(computerControlSessions.controller, "AGENT"), eq(computerControlSessions.fenceToken, input.fenceToken), gt(computerControlSessions.expiresAt, now()))).returning(); if (!session) throw new RelayError("CAPABILITY_DENIED", "Agent input is fenced.", undefined, 409); return { permitId: id("inp"), fenceToken: session.fenceToken }; }
export async function completeComputerInput(input: { accountId: string; controlSessionId: string; fenceToken: number }) { const [session] = await db().update(computerControlSessions).set({ activeInputCount: sql`${computerControlSessions.activeInputCount} - 1`, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), eq(computerControlSessions.fenceToken, input.fenceToken), gt(computerControlSessions.activeInputCount, 0))).returning(); if (!session) throw new RelayError("CAPABILITY_DENIED", "Input permit is stale.", undefined, 409); }
export async function authorizeHumanComputerInput(input: { accountId: string; principalId: string; controlSessionId: string; fenceToken: number }) { const [session] = await db().select({ id: computerControlSessions.id }).from(computerControlSessions).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), eq(computerControlSessions.controller, "HUMAN"), eq(computerControlSessions.humanPrincipalId, input.principalId), eq(computerControlSessions.fenceToken, input.fenceToken), gt(computerControlSessions.expiresAt, now()))).limit(1); if (!session) throw new RelayError("CAPABILITY_DENIED", "Human input is fenced.", undefined, 409); return true; }

export async function takeComputerControl(input: { accountId: string; principalId: string; controlSessionId: string; expectedFenceToken: number }) { await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN", "OPERATOR", "APPROVER"] }); return await withTransaction(async (tx) => { const [session] = await tx.update(computerControlSessions).set({ controller: "HUMAN", humanPrincipalId: input.principalId, fenceToken: sql`${computerControlSessions.fenceToken} + 1`, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), inArray(computerControlSessions.controller, ["AGENT", "PAUSED"]), eq(computerControlSessions.fenceToken, input.expectedFenceToken), eq(computerControlSessions.activeInputCount, 0), gt(computerControlSessions.expiresAt, now()))).returning(); if (!session) throw new RelayError("CAPABILITY_DENIED", "Takeover lost its fence race or input is still active.", undefined, 409); await tx.insert(computerControlEvents).values({ id: id("cce"), accountId: input.accountId, controlSessionId: session.id, principalId: input.principalId, eventType: "control.taken", fenceToken: session.fenceToken }); return { fenceToken: session.fenceToken }; }); }
export async function pauseComputer(input: { accountId: string; principalId: string; controlSessionId: string; expectedFenceToken: number }) { await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN", "OPERATOR", "APPROVER"] }); const [session] = await db().update(computerControlSessions).set({ controller: "PAUSED", humanPrincipalId: null, fenceToken: sql`${computerControlSessions.fenceToken} + 1`, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), eq(computerControlSessions.fenceToken, input.expectedFenceToken), eq(computerControlSessions.activeInputCount, 0), gt(computerControlSessions.expiresAt, now()))).returning(); if (!session) throw new RelayError("CAPABILITY_DENIED", "Pause lost its fence race.", undefined, 409); return { fenceToken: session.fenceToken }; }
export async function setProtectedCredentialEntry(input: { accountId: string; principalId: string; controlSessionId: string; fenceToken: number; enabled: boolean }) { const [session] = await db().update(computerControlSessions).set({ credentialEntryMode: input.enabled, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), eq(computerControlSessions.controller, "HUMAN"), eq(computerControlSessions.humanPrincipalId, input.principalId), eq(computerControlSessions.fenceToken, input.fenceToken))).returning(); if (!session) throw new RelayError("CAPABILITY_DENIED", "Protected entry requires the active human controller.", undefined, 403); await db().insert(computerControlEvents).values({ id: id("cce"), accountId: input.accountId, controlSessionId: input.controlSessionId, principalId: input.principalId, eventType: input.enabled ? "credential_entry.started" : "credential_entry.ended", fenceToken: input.fenceToken, details: { contentSuppressed: true } }); }
export async function disconnectHumanController(input: { accountId: string; principalId: string; controlSessionId: string; fenceToken: number }) { const [session] = await db().update(computerControlSessions).set({ controller: "PAUSED", humanPrincipalId: null, credentialEntryMode: false, fenceToken: sql`${computerControlSessions.fenceToken} + 1`, viewerEpoch: sql`${computerControlSessions.viewerEpoch} + 1`, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), eq(computerControlSessions.controller, "HUMAN"), eq(computerControlSessions.humanPrincipalId, input.principalId), eq(computerControlSessions.fenceToken, input.fenceToken))).returning(); if (!session) return false; await db().update(computerViewerGrants).set({ revokedAt: now() }).where(and(eq(computerViewerGrants.accountId, input.accountId), eq(computerViewerGrants.controlSessionId, input.controlSessionId), isNull(computerViewerGrants.revokedAt))); return true; }

export async function resumeAgentControl(input: { accountId: string; principalId: string; controlSessionId: string; expectedFenceToken: number }, policy: ResumePolicyCheck, integrity: ResumeIntegrityCheck) { await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN", "OPERATOR", "APPROVER"] }); const [current] = await db().select().from(computerControlSessions).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), inArray(computerControlSessions.controller, ["HUMAN", "PAUSED"]), eq(computerControlSessions.fenceToken, input.expectedFenceToken), eq(computerControlSessions.activeInputCount, 0), gt(computerControlSessions.expiresAt, now()))).limit(1); if (!current) throw new RelayError("CAPABILITY_DENIED", "Resume authority is stale.", undefined, 409); const [allowed, inspected] = await Promise.all([policy.authorize({ accountId: input.accountId, taskId: current.taskId, leaseId: current.leaseId, controlSessionId: current.id }), integrity.inspect({ accountId: input.accountId, taskId: current.taskId, leaseId: current.leaseId, providerSessionId: current.providerSessionId })]); if (!allowed || !inspected.safe) throw new RelayError("CAPABILITY_DENIED", "Resume policy or integrity check failed.", undefined, 403); return await withTransaction(async (tx) => { const [session] = await tx.update(computerControlSessions).set({ controller: "AGENT", humanPrincipalId: null, credentialEntryMode: false, lastIntegrityHash: inspected.hash, fenceToken: sql`${computerControlSessions.fenceToken} + 1`, viewerEpoch: sql`${computerControlSessions.viewerEpoch} + 1`, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), inArray(computerControlSessions.controller, ["HUMAN", "PAUSED"]), eq(computerControlSessions.fenceToken, input.expectedFenceToken), eq(computerControlSessions.activeInputCount, 0))).returning(); if (!session) throw new RelayError("CAPABILITY_DENIED", "Resume lost its fence race.", undefined, 409); await tx.update(computerViewerGrants).set({ revokedAt: now() }).where(and(eq(computerViewerGrants.accountId, input.accountId), eq(computerViewerGrants.controlSessionId, input.controlSessionId), isNull(computerViewerGrants.revokedAt))); await tx.insert(computerControlEvents).values({ id: id("cce"), accountId: input.accountId, controlSessionId: input.controlSessionId, principalId: input.principalId, eventType: "control.resumed", fenceToken: session.fenceToken, details: { integrityHash: inspected.hash, policyReevaluated: true } }); return { fenceToken: session.fenceToken, integrityHash: inspected.hash }; }); }
