import { randomBytes } from "node:crypto";
import { and, desc, eq, gt, isNull, sql } from "drizzle-orm";
import { z } from "zod";
import { hashSecret } from "@/lib/crypto";
import { db, withTransaction } from "@/lib/db";
import { capabilityLeases, connectorConnections, connectorDefinitions, connectorOauthFlows, connectorOperations, connectorResources, policyDecisions } from "@/lib/db/schema";
import { RelayError } from "@/lib/errors";
import { id, now } from "@/lib/ids";
import { canonicalHash, capabilityLeaseClaimsSchema } from "@/lib/v2/contracts";
import { verifyAuditSignature, type AuditSigner } from "@/lib/v2/evidence/crypto";
import { redactForEvidence } from "@/lib/v2/evidence/redaction";
import { requireMembership } from "@/lib/v2/identity";

export type ConnectorProvider = "GOOGLE_DRIVE" | "LINEAR";
const providerSchema = z.enum(["GOOGLE_DRIVE", "LINEAR"]);
const driveRestrictions = z.object({ rootFolderIds: z.array(z.string().min(1).max(255)).min(1).max(100), fileIds: z.array(z.string().min(1).max(255)).max(1_000).default([]) }).strict();
const linearRestrictions = z.object({ teamIds: z.array(z.string().min(1).max(255)).min(1).max(100) }).strict();
const restrictionsSchema = z.union([driveRestrictions, linearRestrictions]);
const exactScopes: Record<ConnectorProvider, string[]> = { GOOGLE_DRIVE: ["openid", "email", "https://www.googleapis.com/auth/drive.file"], LINEAR: ["read", "write"] };
const capabilities: Record<ConnectorProvider, string[]> = { GOOGLE_DRIVE: ["connectors.drive.file.search", "connectors.drive.file.read", "connectors.drive.file.create", "connectors.drive.file.update"], LINEAR: ["connectors.linear.issue.search", "connectors.linear.issue.read", "connectors.linear.issue.create", "connectors.linear.issue.update"] };

export const connectorManifestSchema = z.object({ schemaVersion: z.literal("relay.connector.v1"), provider: providerSchema, version: z.string().regex(/^\d+\.\d+$/), oauthScopes: z.array(z.string()).min(1), capabilities: z.array(z.string()).min(1), networkHosts: z.array(z.string()).min(1), secretAccess: z.literal("credential_handle"), supportsReconciliation: z.boolean() }).strict();
export type ConnectorManifest = z.infer<typeof connectorManifestSchema>;

export interface ConnectorCredentialBroker {
  createPkce(input: { accountId: string; provider: ConnectorProvider; state: string; scopes: string[]; redirectUri: string }): Promise<{ authorizationUrl: string; codeVerifierHandle: string }>;
  exchange(input: { accountId: string; provider: ConnectorProvider; code: string; codeVerifierHandle: string; redirectUri: string }): Promise<{ credentialHandle: string; externalAccountId: string; displayName: string; scopes: string[]; accessibleResourceIds: string[]; writableResourceIds: string[] }>;
  revoke(input: { accountId: string; credentialHandle: string }): Promise<void>;
}

export interface ConnectorAdapter {
  readonly provider: ConnectorProvider; readonly version: string;
  inspectAccess(input: { accountId: string; credentialHandle: string }): Promise<{ scopes: string[]; accessibleResourceIds: string[]; writableResourceIds: string[] }>;
  prepare?(input: { accountId: string; credentialHandle: string; capability: string; idempotencyKey: string; parameters: Record<string, unknown> }): Promise<{ providerResourceId?: string }>;
  execute(input: { accountId: string; credentialHandle: string; capability: string; idempotencyKey: string; providerResourceId?: string; parameters: Record<string, unknown> }): Promise<{ state: "SUCCEEDED"; providerResourceId?: string; receipt: Record<string, unknown> } | { state: "PRE_EFFECT_REJECTED"; receipt: Record<string, unknown> } | { state: "EFFECT_UNKNOWN"; receipt: Record<string, unknown> }>;
  reconcile(input: { accountId: string; credentialHandle: string; capability: string; idempotencyKey: string; providerResourceId?: string; parameters: Record<string, unknown>; parametersHash: string }): Promise<{ state: "SUCCEEDED"; providerResourceId: string; receipt: Record<string, unknown> } | { state: "UNKNOWN" }>;
}

export interface ConnectorManifestKeyResolver { publicKeyForKeyId(keyId: string): Promise<string | undefined> }
export class ConnectorRegistry { private readonly adapters = new Map<string, ConnectorAdapter>(); constructor(readonly keyResolver: ConnectorManifestKeyResolver) {} register(adapter: ConnectorAdapter) { this.adapters.set(`${adapter.provider}@${adapter.version}`, adapter); } resolve(provider: ConnectorProvider, version: string) { return this.adapters.get(`${provider}@${version}`); } }

function sameSet(left: string[], right: string[]) { return left.length === right.length && [...left].sort().every((value, index) => value === [...right].sort()[index]); }
function opaqueHandle(value: string) { return /^vlt_[A-Za-z0-9_-]{8,}$/.test(value); }
function parseRestrictions(provider: ConnectorProvider, input: unknown) { return provider === "GOOGLE_DRIVE" ? driveRestrictions.parse(input) : linearRestrictions.parse(input); }

export function qualifyConnector(manifestInput: unknown, adapter: ConnectorAdapter) {
  const manifest = connectorManifestSchema.parse(manifestInput); const failures: string[] = [];
  if (adapter.provider !== manifest.provider || adapter.version !== manifest.version) failures.push("adapter_identity_mismatch");
  if (!sameSet(manifest.oauthScopes, exactScopes[manifest.provider])) failures.push("oauth_scope_mismatch");
  if (!sameSet(manifest.capabilities, capabilities[manifest.provider])) failures.push("capability_set_mismatch");
  for (const method of ["inspectAccess", "execute", "reconcile"] as const) if (typeof adapter[method] !== "function") failures.push(`missing_${method}`);
  return { qualified: failures.length === 0, failures, manifest };
}

export async function publishConnector(manifestInput: unknown, adapter: ConnectorAdapter, signer: AuditSigner) {
  const result = qualifyConnector(manifestInput, adapter); if (!result.qualified) throw new RelayError("INVALID_INPUT", `Connector conformance failed: ${result.failures.join(",")}`);
  const manifestHash = canonicalHash(result.manifest); const signature = await signer.sign(manifestHash); const definitionId = id("cnd");
  await db().insert(connectorDefinitions).values({ id: definitionId, provider: result.manifest.provider, version: result.manifest.version, manifest: result.manifest, manifestHash, signature, signingKeyId: signer.keyId }); return { definitionId, manifestHash, signature };
}

export async function beginConnectorOauth(input: { accountId: string; principalId: string; provider: ConnectorProvider; redirectUri: string; restrictions: unknown }, broker: ConnectorCredentialBroker) {
  await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN", "OPERATOR"] }); const provider = providerSchema.parse(input.provider); const restrictions = parseRestrictions(provider, input.restrictions); const state = `cos_${randomBytes(32).toString("base64url")}`; const scopes = exactScopes[provider];
  const pkce = await broker.createPkce({ accountId: input.accountId, provider, state, scopes, redirectUri: input.redirectUri }); if (!opaqueHandle(pkce.codeVerifierHandle)) throw new RelayError("INTERNAL_ERROR", "OAuth broker returned an invalid verifier handle.", undefined, 500);
  const flowId = id("cof"); const expiresAt = new Date(Date.now() + 10 * 60_000).toISOString(); await db().insert(connectorOauthFlows).values({ id: flowId, accountId: input.accountId, principalId: input.principalId, provider, stateHash: hashSecret(state), codeVerifierHandle: pkce.codeVerifierHandle, redirectUri: input.redirectUri, requestedScopes: scopes, restrictions, expiresAt }); return { flowId, state, authorizationUrl: pkce.authorizationUrl, scopes, restrictions, expiresAt };
}

export async function completeConnectorOauth(input: { accountId: string; principalId: string; provider: ConnectorProvider; state: string; code: string }, broker: ConnectorCredentialBroker) {
  await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN", "OPERATOR"] }); const timestamp = now();
  const flow = await withTransaction(async (transaction) => { const [row] = await transaction.select().from(connectorOauthFlows).where(and(eq(connectorOauthFlows.accountId, input.accountId), eq(connectorOauthFlows.principalId, input.principalId), eq(connectorOauthFlows.provider, input.provider), eq(connectorOauthFlows.stateHash, hashSecret(input.state)), isNull(connectorOauthFlows.consumedAt), gt(connectorOauthFlows.expiresAt, timestamp))).limit(1); if (!row) throw new RelayError("INVALID_CREDENTIAL", "OAuth state is invalid, expired, consumed, or belongs to another account.", undefined, 401); const [claimed] = await transaction.update(connectorOauthFlows).set({ consumedAt: timestamp }).where(and(eq(connectorOauthFlows.id, row.id), isNull(connectorOauthFlows.consumedAt))).returning(); if (!claimed) throw new RelayError("INVALID_CREDENTIAL", "OAuth state was already consumed.", undefined, 409); return row; });
  const exchanged = await broker.exchange({ accountId: input.accountId, provider: input.provider, code: input.code, codeVerifierHandle: flow.codeVerifierHandle, redirectUri: flow.redirectUri }); if (!opaqueHandle(exchanged.credentialHandle) || !sameSet(exchanged.scopes, flow.requestedScopes)) throw new RelayError("CAPABILITY_DENIED", "OAuth result has invalid credential storage or scope drift.", undefined, 403);
  const restrictions = parseRestrictions(input.provider, flow.restrictions); const selected = "rootFolderIds" in restrictions ? [...restrictions.rootFolderIds, ...restrictions.fileIds] : restrictions.teamIds; if (selected.some((resourceId) => !exchanged.accessibleResourceIds.includes(resourceId) || !exchanged.writableResourceIds.includes(resourceId))) throw new RelayError("CAPABILITY_DENIED", "Selected connector resources are not readable and writable.", undefined, 403);
  const [definition] = await db().select().from(connectorDefinitions).where(and(eq(connectorDefinitions.provider, input.provider), eq(connectorDefinitions.status, "ACTIVE"))).orderBy(desc(connectorDefinitions.createdAt)).limit(1); if (!definition) throw new RelayError("CONNECTION_REQUIRED", "A qualified connector definition is unavailable.", undefined, 503);
  const snapshot = { scopes: [...exchanged.scopes].sort(), accessibleResourceIds: [...exchanged.accessibleResourceIds].sort(), writableResourceIds: [...exchanged.writableResourceIds].sort() }; const connectionId = id("cnx"); const [saved] = await db().insert(connectorConnections).values({ id: connectionId, accountId: input.accountId, definitionId: definition.id, provider: input.provider, externalAccountId: exchanged.externalAccountId, displayName: exchanged.displayName, scopes: exchanged.scopes, restrictions, credentialHandle: exchanged.credentialHandle, permissionSnapshot: snapshot, permissionSnapshotHash: canonicalHash(snapshot), lastVerifiedAt: timestamp }).onConflictDoUpdate({ target: [connectorConnections.accountId, connectorConnections.provider], set: { definitionId: definition.id, externalAccountId: exchanged.externalAccountId, displayName: exchanged.displayName, scopes: exchanged.scopes, restrictions, credentialHandle: exchanged.credentialHandle, permissionSnapshot: snapshot, permissionSnapshotHash: canonicalHash(snapshot), status: "CONNECTED", lastVerifiedAt: timestamp, updatedAt: timestamp, revokedAt: null } }).returning({ id: connectorConnections.id });
  return { connectionId: saved!.id, provider: input.provider, displayName: exchanged.displayName, scopes: exchanged.scopes, restrictions };
}

export async function revokeConnector(input: { accountId: string; principalId: string; connectionId: string }, broker: ConnectorCredentialBroker) {
  await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN"] }); const [connection] = await db().select().from(connectorConnections).where(and(eq(connectorConnections.accountId, input.accountId), eq(connectorConnections.id, input.connectionId), eq(connectorConnections.status, "CONNECTED"))).limit(1); if (!connection) throw new RelayError("CONNECTION_REQUIRED", "Connector is unavailable.", undefined, 404); await db().update(connectorConnections).set({ status: "DISCONNECTED", revokedAt: now(), updatedAt: now() }).where(and(eq(connectorConnections.accountId, input.accountId), eq(connectorConnections.id, input.connectionId))); try { await broker.revoke({ accountId: input.accountId, credentialHandle: connection.credentialHandle }); return { disconnected: true, providerRevocation: "CONFIRMED" as const }; } catch { return { disconnected: true, providerRevocation: "PENDING" as const }; }
}

async function permitted(connection: typeof connectorConnections.$inferSelect, capability: string, parameters: Record<string, unknown>) {
  if (!capabilities[connection.provider].includes(capability)) return false; const restrictions = restrictionsSchema.parse(connection.restrictions);
  if (connection.provider === "GOOGLE_DRIVE" && "rootFolderIds" in restrictions) { const containerId = String(parameters.containerId ?? ""); const resourceId = parameters.resourceId === undefined ? undefined : String(parameters.resourceId); if (!restrictions.rootFolderIds.includes(containerId)) return false; if (!resourceId || restrictions.fileIds.includes(resourceId)) return true; const [known] = await db().select({ metadata: connectorResources.metadata }).from(connectorResources).where(and(eq(connectorResources.accountId, connection.accountId), eq(connectorResources.connectionId, connection.id), eq(connectorResources.externalId, resourceId), eq(connectorResources.containerExternalId, containerId))).limit(1); return (known?.metadata as { appCreated?: boolean } | undefined)?.appCreated === true; }
  if (connection.provider === "LINEAR" && "teamIds" in restrictions) { const write = capability.endsWith(".create") || capability.endsWith(".update"); const allowedFields = capability.endsWith(".update") ? ["teamId", "resourceId", "title", "description"] : ["teamId", "title", "description"]; return restrictions.teamIds.includes(String(parameters.teamId ?? "")) && (!write || !Object.keys(parameters).some((key) => !allowedFields.includes(key))); }
  return false;
}

async function activeConnector(accountId: string, connectionId: string, registry: ConnectorRegistry) {
  const [row] = await db().select({ connection: connectorConnections, definition: connectorDefinitions }).from(connectorConnections).innerJoin(connectorDefinitions, eq(connectorDefinitions.id, connectorConnections.definitionId)).where(and(eq(connectorConnections.accountId, accountId), eq(connectorConnections.id, connectionId), eq(connectorConnections.status, "CONNECTED"), isNull(connectorConnections.revokedAt), eq(connectorDefinitions.status, "ACTIVE"))).limit(1); if (!row) throw new RelayError("CONNECTION_REQUIRED", "Connector is revoked or unavailable.", undefined, 404); const manifest = connectorManifestSchema.parse(row.definition.manifest); const publicKey = await registry.keyResolver.publicKeyForKeyId(row.definition.signingKeyId); if (canonicalHash(manifest) !== row.definition.manifestHash || !publicKey || !verifyAuditSignature(publicKey, row.definition.manifestHash, row.definition.signature)) throw new RelayError("CAPABILITY_DENIED", "Connector manifest integrity failed.", undefined, 503); const adapter = registry.resolve(row.connection.provider, manifest.version); if (!adapter || !qualifyConnector(manifest, adapter).qualified) throw new RelayError("CONNECTION_REQUIRED", "Qualified connector adapter is unavailable.", undefined, 503); return { ...row, manifest, adapter };
}

async function verifyPermissions(row: Awaited<ReturnType<typeof activeConnector>>) {
  const observed = await row.adapter.inspectAccess({ accountId: row.connection.accountId, credentialHandle: row.connection.credentialHandle }); const restrictions = restrictionsSchema.parse(row.connection.restrictions); const selected = "rootFolderIds" in restrictions ? [...restrictions.rootFolderIds, ...restrictions.fileIds] : restrictions.teamIds;
  if (!sameSet(observed.scopes, row.connection.scopes) || selected.some((value) => !observed.accessibleResourceIds.includes(value) || !observed.writableResourceIds.includes(value))) { await db().update(connectorConnections).set({ status: "ERROR", updatedAt: now() }).where(and(eq(connectorConnections.accountId, row.connection.accountId), eq(connectorConnections.id, row.connection.id))); throw new RelayError("CAPABILITY_DENIED", "Connector permission drift detected; reconnect is required.", undefined, 403); }
  const snapshot = { scopes: [...observed.scopes].sort(), accessibleResourceIds: [...observed.accessibleResourceIds].sort(), writableResourceIds: [...observed.writableResourceIds].sort() }; await db().update(connectorConnections).set({ permissionSnapshot: snapshot, permissionSnapshotHash: canonicalHash(snapshot), lastVerifiedAt: now(), updatedAt: now() }).where(and(eq(connectorConnections.accountId, row.connection.accountId), eq(connectorConnections.id, row.connection.id)));
}

async function authorizeOperation(input: { accountId: string; connectionId: string; taskId: string; actionIntentId: string; leaseId: string; capability: string; parameters: Record<string, unknown> }, registry: ConnectorRegistry) {
  const row = await activeConnector(input.accountId, input.connectionId, registry); if (!await permitted(row.connection, input.capability, input.parameters)) throw new RelayError("CAPABILITY_DENIED", "Connector resource or operation is outside configured restrictions.", undefined, 403); const [binding] = await db().select({ lease: capabilityLeases }).from(capabilityLeases).innerJoin(policyDecisions, and(eq(policyDecisions.accountId, capabilityLeases.accountId), eq(policyDecisions.id, capabilityLeases.policyDecisionId))).where(and(eq(capabilityLeases.accountId, input.accountId), eq(capabilityLeases.id, input.leaseId), eq(capabilityLeases.taskId, input.taskId), eq(policyDecisions.actionIntentId, input.actionIntentId), eq(capabilityLeases.status, "ACTIVE"), gt(capabilityLeases.expiresAt, now()), isNull(capabilityLeases.revokedAt))).limit(1); const lease = binding?.lease; if (!lease) throw new RelayError("CAPABILITY_DENIED", "Active connector lease is unavailable.", undefined, 403); const claims = capabilityLeaseClaimsSchema.parse(lease.claims); const expected = canonicalHash({ capability: claims.capability, resource: claims.resource, parameters: input.parameters }); if (claims.accountId !== input.accountId || claims.taskId !== input.taskId || claims.jti !== input.leaseId || claims.capability.name !== input.capability || claims.actionHash !== expected) throw new RelayError("CAPABILITY_DENIED", "Connector action differs from lease authority.", undefined, 403); await verifyPermissions(row); return row;
}

function assertOperationReplay(operation: typeof connectorOperations.$inferSelect, input: { connectionId: string; taskId: string; actionIntentId: string; leaseId: string; capability: string; parameters: Record<string, unknown> }) { if (operation.connectionId !== input.connectionId || operation.taskId !== input.taskId || operation.actionIntentId !== input.actionIntentId || operation.leaseId !== input.leaseId || operation.capability !== input.capability || operation.parametersHash !== canonicalHash(input.parameters)) throw new RelayError("INVALID_INPUT", "Connector idempotency key was reused with different authority or parameters.", undefined, 409); }

export async function executeConnector(input: { accountId: string; connectionId: string; taskId: string; actionIntentId: string; leaseId: string; capability: string; parameters: Record<string, unknown>; idempotencyKey: string }, registry: ConnectorRegistry) {
  const [replay] = await db().select().from(connectorOperations).where(and(eq(connectorOperations.accountId, input.accountId), eq(connectorOperations.idempotencyKey, input.idempotencyKey))).limit(1); if (replay) { assertOperationReplay(replay, input); return { operationId: replay.id, status: replay.status, providerResourceId: replay.providerResourceId, idempotentReplay: true }; }
  const row = await authorizeOperation(input, registry); const prepared = await row.adapter.prepare?.({ accountId: input.accountId, credentialHandle: row.connection.credentialHandle, capability: input.capability, idempotencyKey: input.idempotencyKey, parameters: input.parameters }); const operationId = id("cop"); const [operation] = await withTransaction(async (transaction) => { await transaction.execute(sql`SELECT pg_advisory_xact_lock(hashtextextended(${`connector:${input.accountId}:${input.idempotencyKey}`}, 0))`); const [existing] = await transaction.select().from(connectorOperations).where(and(eq(connectorOperations.accountId, input.accountId), eq(connectorOperations.idempotencyKey, input.idempotencyKey))).limit(1); if (existing) { assertOperationReplay(existing, input); return [existing]; } const [used] = await transaction.update(capabilityLeases).set({ callCount: sql`${capabilityLeases.callCount} + 1` }).where(and(eq(capabilityLeases.accountId, input.accountId), eq(capabilityLeases.id, input.leaseId), eq(capabilityLeases.status, "ACTIVE"), sql`${capabilityLeases.callCount} + ${capabilityLeases.delegatedCallCount} < ${capabilityLeases.maxCalls}`)).returning({ callCount: capabilityLeases.callCount, maxCalls: capabilityLeases.maxCalls, delegatedCallCount: capabilityLeases.delegatedCallCount }); if (!used) throw new RelayError("CAPABILITY_DENIED", "Connector lease call limit is exhausted.", undefined, 409); if (used.callCount + used.delegatedCallCount >= used.maxCalls) await transaction.update(capabilityLeases).set({ status: "EXHAUSTED" }).where(and(eq(capabilityLeases.accountId, input.accountId), eq(capabilityLeases.id, input.leaseId))); return await transaction.insert(connectorOperations).values({ id: operationId, accountId: input.accountId, connectionId: input.connectionId, taskId: input.taskId, actionIntentId: input.actionIntentId, leaseId: input.leaseId, capability: input.capability, resourceHash: canonicalHash({ connectionId: input.connectionId, provider: row.connection.provider, restrictions: row.connection.restrictions }), parameters: input.parameters, parametersHash: canonicalHash(input.parameters), idempotencyKey: input.idempotencyKey, providerResourceId: prepared?.providerResourceId, status: "RUNNING", attemptCount: 1 }).returning(); }); if (operation!.id !== operationId) return { operationId: operation!.id, status: operation!.status, providerResourceId: operation!.providerResourceId, idempotentReplay: true };
  const result = await row.adapter.execute({ accountId: input.accountId, credentialHandle: row.connection.credentialHandle, capability: input.capability, idempotencyKey: input.idempotencyKey, providerResourceId: prepared?.providerResourceId, parameters: input.parameters }); const status = result.state === "SUCCEEDED" ? "SUCCEEDED" : result.state === "PRE_EFFECT_REJECTED" ? "FAILED" : "EFFECT_UNKNOWN"; const providerResourceId = "providerResourceId" in result ? result.providerResourceId : prepared?.providerResourceId; await db().update(connectorOperations).set({ status, providerResourceId, receipt: redactForEvidence({ ...result.receipt, effectState: result.state }), updatedAt: now() }).where(and(eq(connectorOperations.accountId, input.accountId), eq(connectorOperations.id, operationId))); if (status === "SUCCEEDED" && providerResourceId) await recordConnectorResource({ accountId: input.accountId, connectionId: input.connectionId, providerType: input.capability.includes("drive.file") ? "file" : "issue", externalId: providerResourceId, containerExternalId: String(input.parameters.containerId ?? input.parameters.teamId ?? ""), metadata: { appCreated: input.capability.endsWith(".create") }, permissions: row.connection.restrictions }); return { operationId, status, providerResourceId, idempotentReplay: false };
}

export async function reconcileConnector(input: { accountId: string; operationId: string }, registry: ConnectorRegistry) {
  const [operation] = await db().select().from(connectorOperations).where(and(eq(connectorOperations.accountId, input.accountId), eq(connectorOperations.id, input.operationId), eq(connectorOperations.status, "EFFECT_UNKNOWN"))).limit(1); if (!operation) throw new RelayError("CAPABILITY_DENIED", "Connector reconciliation is unavailable.", undefined, 409); const row = await activeConnector(input.accountId, operation.connectionId, registry); await verifyPermissions(row); const parameters = z.record(z.unknown()).parse(operation.parameters); const result = await row.adapter.reconcile({ accountId: input.accountId, credentialHandle: row.connection.credentialHandle, capability: operation.capability, idempotencyKey: operation.idempotencyKey, providerResourceId: operation.providerResourceId ?? undefined, parameters, parametersHash: operation.parametersHash }); if (result.state === "UNKNOWN") return { operationId: operation.id, status: "EFFECT_UNKNOWN" as const }; await db().update(connectorOperations).set({ status: "SUCCEEDED", providerResourceId: result.providerResourceId, receipt: redactForEvidence({ ...result.receipt, reconciled: true }), updatedAt: now() }).where(and(eq(connectorOperations.accountId, input.accountId), eq(connectorOperations.id, operation.id))); await recordConnectorResource({ accountId: input.accountId, connectionId: operation.connectionId, providerType: operation.capability.includes("drive.file") ? "file" : "issue", externalId: result.providerResourceId, containerExternalId: String(parameters.containerId ?? parameters.teamId ?? ""), metadata: { appCreated: operation.capability.endsWith(".create") }, permissions: row.connection.restrictions }); return { operationId: operation.id, status: "SUCCEEDED" as const, providerResourceId: result.providerResourceId };
}

export async function recordConnectorResource(input: { accountId: string; connectionId: string; providerType: string; externalId: string; containerExternalId: string; metadata: Record<string, unknown>; permissions: unknown }) { const connection = await db().select({ id: connectorConnections.id }).from(connectorConnections).where(and(eq(connectorConnections.accountId, input.accountId), eq(connectorConnections.id, input.connectionId))).limit(1); if (!connection.length) throw new RelayError("CONNECTION_REQUIRED", "Connector is unavailable.", undefined, 404); const resourceId = id("crs"); await db().insert(connectorResources).values({ id: resourceId, accountId: input.accountId, connectionId: input.connectionId, providerType: input.providerType, externalId: input.externalId, containerExternalId: input.containerExternalId, metadata: input.metadata, permissionsHash: canonicalHash(input.permissions), lastVerifiedAt: now() }).onConflictDoUpdate({ target: [connectorResources.connectionId, connectorResources.providerType, connectorResources.externalId], set: { containerExternalId: input.containerExternalId, metadata: input.metadata, permissionsHash: canonicalHash(input.permissions), lastVerifiedAt: now(), updatedAt: now() } }); return { resourceId }; }

export async function listConnectorConnections(accountId: string) { return await db().select({ id: connectorConnections.id, provider: connectorConnections.provider, displayName: connectorConnections.displayName, status: connectorConnections.status, scopes: connectorConnections.scopes, restrictions: connectorConnections.restrictions, lastVerifiedAt: connectorConnections.lastVerifiedAt }).from(connectorConnections).where(eq(connectorConnections.accountId, accountId)); }
