import { randomBytes } from "node:crypto";
import { and, asc, eq, gt, inArray, sql } from "drizzle-orm";
import { z } from "zod";
import { hashSecret } from "@/lib/crypto";
import { db, withTransaction } from "@/lib/db";
import { approvalRequests, budgetReservations, budgets, computerControlEvents, computerControlSessions, financialAccounts, financialTransactions, paymentCredentialReferences, purchaseCheckoutPermits, purchaseIntents, purchaseReceipts } from "@/lib/db/schema";
import { RelayError } from "@/lib/errors";
import { id, now } from "@/lib/ids";
import { consumeApprovalInTransaction } from "@/lib/v2/approvals";
import { markBudgetReservationUnknown, reconcileBudgetReservation, releaseBudgetReservation, reserveBudget } from "@/lib/v2/budgets";
import { actionIntentSchema, approvalScopeSchema, canonicalHash, type ActionIntent } from "@/lib/v2/contracts";
import { appendAuditRecordInTransaction } from "@/lib/v2/evidence/audit";
import type { AuditSigner } from "@/lib/v2/evidence/crypto";
import { redactForEvidence } from "@/lib/v2/evidence/redaction";
import { requireMembership } from "@/lib/v2/identity";

const amountSchema = z.string().regex(/^(?:0|[1-9]\d*)(?:\.\d{1,9})?$/);
const positiveAmountSchema = amountSchema.refine((value) => decimalUnits(value) > 0n, "must be greater than zero");
const currencySchema = z.string().regex(/^[A-Z]{3}$/);
const itemSchema = z.object({ reference: z.string().min(1).max(255), description: z.string().min(1).max(1_000), quantity: z.number().int().positive().max(100_000), unitAmount: amountSchema }).strict();
const purchaseSchema = z.object({ merchantId: z.string().min(1).max(512), merchantName: z.string().min(1).max(512), currency: currencySchema, requestedAmount: positiveAmountSchema, taxShippingTolerance: amountSchema.default("0"), items: z.array(itemSchema).min(1).max(1_000), credentialReferenceId: z.string().regex(/^pcr_[a-zA-Z0-9]{8,}$/) }).strict();
const RAW_PAYMENT_KEY = /^(?:pan|cvv|cvc|cardNumber|card_number|routingNumber|routing_number|bankAccount|bank_account|accountNumber|account_number|iban)$/i;
const PAYMENT_NUMBER = /(?:\d[ -]?){12,18}\d/g;
const SCALE = 1_000_000_000n;

function decimalUnits(value: string) { const [whole, fraction = ""] = value.split("."); return BigInt(whole!) * SCALE + BigInt(fraction.padEnd(9, "0")); }
function decimalFromUnits(value: bigint) { return `${value / SCALE}.${(value % SCALE).toString().padStart(9, "0")}`; }
function actionMaterial(action: ActionIntent) { return { capability: action.capability, resource: action.resource, parameters: action.parameters }; }
function purchaseMaterial(value: z.infer<typeof purchaseSchema>) { return { merchantId: value.merchantId, merchantName: value.merchantName, currency: value.currency, requestedAmount: value.requestedAmount, taxShippingTolerance: value.taxShippingTolerance, items: value.items, credentialReferenceId: value.credentialReferenceId }; }
function isLuhn(value: string) { const digits = value.replace(/\D/g, ""); if (digits.length < 13 || digits.length > 19 || /^(\d)\1+$/.test(digits)) return false; let sum = 0; let alternate = false; for (let index = digits.length - 1; index >= 0; index -= 1) { let digit = Number(digits[index]); if (alternate && (digit *= 2) > 9) digit -= 9; sum += digit; alternate = !alternate; } return sum % 10 === 0; }

export function assertNoRawPaymentCredentials(value: unknown, key = "root"): void {
  if (RAW_PAYMENT_KEY.test(key)) throw new RelayError("INVALID_INPUT", "Raw payment credentials are prohibited.");
  if (typeof value === "string") { for (const candidate of value.match(PAYMENT_NUMBER) ?? []) if (isLuhn(candidate)) throw new RelayError("INVALID_INPUT", "Raw payment credentials are prohibited."); return; }
  if (Array.isArray(value)) { for (const entry of value) assertNoRawPaymentCredentials(entry, key); return; }
  if (value && typeof value === "object") for (const [entryKey, entry] of Object.entries(value)) assertNoRawPaymentCredentials(entry, entryKey);
}

export interface FinancialAggregatorAdapter {
  provider: string;
  version: string;
  qualificationStatus: "QUALIFIED";
  read(input: { accountId: string }): Promise<{ accounts: Array<{ externalAccountId: string; displayName: string; kind: string; currency: string; balance?: string; balanceAsOf?: string }>; transactions: Array<{ externalAccountId: string; providerTransactionId: string; amount: string; currency: string; merchant?: string; description?: string; occurredAt: string; providerData?: Record<string, unknown> }> }>;
}

export class FinancialAggregatorRegistry {
  readonly #adapters = new Map<string, FinancialAggregatorAdapter>();
  register(adapter: FinancialAggregatorAdapter) { if (adapter.qualificationStatus !== "QUALIFIED") throw new RelayError("CAPABILITY_DENIED", "Only a qualified read-only financial adapter may be registered.", undefined, 403); if (this.#adapters.has(adapter.provider)) throw new RelayError("INVALID_INPUT", "Financial adapter is already registered.", undefined, 409); this.#adapters.set(adapter.provider, adapter); }
  require(provider: string) { const adapter = this.#adapters.get(provider); if (!adapter) throw new RelayError("CONNECTION_REQUIRED", "No qualified financial aggregator is enabled.", undefined, 503); return adapter; }
}

export async function syncReadOnlyFinancialData(input: { accountId: string; principalId: string; provider: string }, registry: FinancialAggregatorRegistry) {
  await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN", "AUDITOR"] });
  const adapter = registry.require(input.provider); const result = await adapter.read({ accountId: input.accountId }); assertNoRawPaymentCredentials(result);
  return await withTransaction(async (transaction) => {
    const accountIds = new Map<string, string>();
    for (const account of result.accounts) {
      const parsed = z.object({ externalAccountId: z.string().min(1), displayName: z.string().min(1), kind: z.string().min(1), currency: currencySchema, balance: amountSchema.optional(), balanceAsOf: z.string().datetime({ offset: true }).optional() }).strict().parse(account);
      const accountId = id("fac"); const [row] = await transaction.insert(financialAccounts).values({ id: accountId, accountId: input.accountId, provider: adapter.provider, ...parsed }).onConflictDoUpdate({ target: [financialAccounts.accountId, financialAccounts.provider, financialAccounts.externalAccountId], set: { displayName: parsed.displayName, kind: parsed.kind, currency: parsed.currency, balance: parsed.balance, balanceAsOf: parsed.balanceAsOf, status: "ACTIVE", updatedAt: now() } }).returning({ id: financialAccounts.id, externalAccountId: financialAccounts.externalAccountId }); accountIds.set(row!.externalAccountId, row!.id);
    }
    for (const item of result.transactions) {
      const parsed = z.object({ externalAccountId: z.string().min(1), providerTransactionId: z.string().min(1), amount: amountSchema, currency: currencySchema, merchant: z.string().max(512).optional(), description: z.string().max(2_000).optional(), occurredAt: z.string().datetime({ offset: true }), providerData: z.record(z.unknown()).optional() }).strict().parse(item); const financialAccountId = accountIds.get(parsed.externalAccountId); if (!financialAccountId) throw new RelayError("INVALID_INPUT", "Transaction references an account outside this sync.");
      await transaction.insert(financialTransactions).values({ id: id("ftx"), accountId: input.accountId, financialAccountId, providerTransactionId: parsed.providerTransactionId, amount: parsed.amount, currency: parsed.currency, merchant: parsed.merchant, description: parsed.description, occurredAt: parsed.occurredAt, providerData: redactForEvidence(parsed.providerData ?? {}) }).onConflictDoNothing();
    }
    return { accountCount: result.accounts.length, transactionCount: result.transactions.length };
  });
}

export async function registerPaymentCredentialReference(input: { accountId: string; principalId: string; provider: string; credentialHandle: string; displayLabel: string }, signer: AuditSigner) {
  await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN"] }); assertNoRawPaymentCredentials(input);
  const parsed = z.object({ provider: z.string().min(1).max(128), credentialHandle: z.string().regex(/^vlt_[a-zA-Z0-9._~-]{8,}$/), displayLabel: z.string().min(1).max(255) }).parse(input); const credentialReferenceId = id("pcr");
  await withTransaction(async (transaction) => { await transaction.insert(paymentCredentialReferences).values({ id: credentialReferenceId, accountId: input.accountId, ...parsed }); await appendAuditRecordInTransaction(transaction, { accountId: input.accountId, actorPrincipalId: input.principalId, eventType: "money.credential_reference.registered", outcome: "SUCCESS", details: { credentialReferenceId, provider: parsed.provider, displayLabel: parsed.displayLabel } }, signer); }); return { credentialReferenceId };
}

export async function createPurchaseIntent(input: { accountId: string; action: ActionIntent; leafBudgetId: string; purchase: z.input<typeof purchaseSchema>; idempotencyKey: string; expiresAt: string }, signer: AuditSigner) {
  assertNoRawPaymentCredentials(input); const action = actionIntentSchema.parse(input.action); const purchase = purchaseSchema.parse(input.purchase); const material = purchaseMaterial(purchase);
  if (action.accountId !== input.accountId || action.capability.name !== "money.purchase.request" || action.capability.version !== "1.0" || action.resource.type !== "purchase" || canonicalHash(actionMaterial(action)) !== action.canonicalHash || canonicalHash(action.parameters) !== canonicalHash(material)) throw new RelayError("INVALID_INPUT", "Purchase action is not an immutable canonical purchase request.");
  const [credential] = await db().select({ id: paymentCredentialReferences.id }).from(paymentCredentialReferences).where(and(eq(paymentCredentialReferences.accountId, input.accountId), eq(paymentCredentialReferences.id, purchase.credentialReferenceId), eq(paymentCredentialReferences.status, "ACTIVE"))).limit(1); if (!credential) throw new RelayError("CAPABILITY_DENIED", "Payment credential reference is unavailable in this account.", undefined, 403);
  const [existing] = await db().select().from(purchaseIntents).where(and(eq(purchaseIntents.accountId, input.accountId), eq(purchaseIntents.idempotencyKey, input.idempotencyKey))).limit(1); if (existing) { if (existing.actionHash !== action.canonicalHash) throw new RelayError("INVALID_INPUT", "Purchase idempotency key was reused with a different action.", undefined, 409); return { purchaseIntentId: existing.id, reservationId: existing.budgetReservationId, idempotentReplay: true }; }
  const authorizedMaximum = decimalFromUnits(decimalUnits(purchase.requestedAmount) + decimalUnits(purchase.taxShippingTolerance)); const reservation = await reserveBudget({ accountId: input.accountId, leafBudgetId: input.leafBudgetId, agentId: action.agentId, taskId: action.taskId, actionIntentId: action.id, amount: authorizedMaximum, idempotencyKey: `purchase:${input.idempotencyKey}`, expiresAt: input.expiresAt }, signer); const purchaseIntentId = id("pin");
  try { await withTransaction(async (transaction) => { await transaction.insert(purchaseIntents).values({ id: purchaseIntentId, accountId: input.accountId, agentId: action.agentId, runtimeClientId: action.runtimeClientId, taskId: action.taskId, actionIntentId: action.id, actionHash: action.canonicalHash, actionSnapshot: action, merchantId: purchase.merchantId, merchantName: purchase.merchantName, currency: purchase.currency, requestedAmount: purchase.requestedAmount, taxShippingTolerance: purchase.taxShippingTolerance, authorizedMaximum, items: purchase.items, credentialReferenceId: purchase.credentialReferenceId, budgetReservationId: reservation.reservationId, idempotencyKey: input.idempotencyKey }); await appendAuditRecordInTransaction(transaction, { accountId: input.accountId, agentId: action.agentId, runtimeClientId: action.runtimeClientId, taskId: action.taskId, actionIntentId: action.id, eventType: "money.purchase.requested", outcome: "PENDING_APPROVAL", details: { purchaseIntentId, merchantId: purchase.merchantId, merchantName: purchase.merchantName, currency: purchase.currency, requestedAmount: purchase.requestedAmount, taxShippingTolerance: purchase.taxShippingTolerance, authorizedMaximum, budgetReservationId: reservation.reservationId } }, signer); }); } catch (error) { await releaseBudgetReservation({ accountId: input.accountId, reservationId: reservation.reservationId }, signer).catch(() => undefined); throw error; }
  return { purchaseIntentId, reservationId: reservation.reservationId, idempotentReplay: false };
}

export async function attachPurchaseApproval(input: { accountId: string; purchaseIntentId: string; approvalRequestId: string }) {
  const [request] = await db().select().from(approvalRequests).where(and(eq(approvalRequests.accountId, input.accountId), eq(approvalRequests.id, input.approvalRequestId), inArray(approvalRequests.status, ["PENDING", "APPROVED"]))).limit(1); const [purchase] = await db().select().from(purchaseIntents).where(and(eq(purchaseIntents.accountId, input.accountId), eq(purchaseIntents.id, input.purchaseIntentId), eq(purchaseIntents.status, "PENDING_APPROVAL"))).limit(1);
  if (!request || !purchase || request.actionIntentId !== purchase.actionIntentId || request.actionHash !== purchase.actionHash || request.effectClass !== "financial" || !request.allowedScopes.includes("once")) throw new RelayError("CAPABILITY_DENIED", "A matching once-capable financial approval is required.", undefined, 403);
  await db().update(purchaseIntents).set({ approvalRequestId: request.id, status: request.status === "APPROVED" ? "READY_FOR_CHECKOUT" : "PENDING_APPROVAL", updatedAt: now() }).where(and(eq(purchaseIntents.accountId, input.accountId), eq(purchaseIntents.id, purchase.id))); return { attached: true };
}

export async function beginProtectedHumanCheckout(input: { accountId: string; purchaseIntentId: string; principalId: string; controlSessionId: string; expectedFenceToken: number; permitTtlSeconds?: number }, signer: AuditSigner) {
  await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN", "APPROVER"] }); const token = `pco_${randomBytes(32).toString("base64url")}`; const timestamp = now();
  return await withTransaction(async (transaction) => {
    const [purchase] = await transaction.select().from(purchaseIntents).where(and(eq(purchaseIntents.accountId, input.accountId), eq(purchaseIntents.id, input.purchaseIntentId), inArray(purchaseIntents.status, ["PENDING_APPROVAL", "READY_FOR_CHECKOUT"]))).limit(1); if (!purchase?.approvalRequestId) throw new RelayError("CAPABILITY_DENIED", "Purchase approval is unavailable.", undefined, 403);
    const [approval] = await transaction.select().from(approvalRequests).where(and(eq(approvalRequests.accountId, input.accountId), eq(approvalRequests.id, purchase.approvalRequestId), eq(approvalRequests.status, "APPROVED"), gt(approvalRequests.expiresAt, timestamp))).limit(1); const scope = approval ? approvalScopeSchema.parse(approval.approvedScope) : undefined; if (!approval || scope?.kind !== "once" || scope.actionHash !== purchase.actionHash) throw new RelayError("CAPABILITY_DENIED", "V2 purchases require a current once approval.", undefined, 403);
    const [reservation] = await transaction.select().from(budgetReservations).innerJoin(budgets, and(eq(budgets.id, budgetReservations.leafBudgetId), eq(budgets.accountId, budgetReservations.accountId))).where(and(eq(budgetReservations.accountId, input.accountId), eq(budgetReservations.id, purchase.budgetReservationId), eq(budgetReservations.status, "RESERVED"), gt(budgetReservations.expiresAt, timestamp), eq(budgets.dimension, "PURCHASE_AMOUNT"), eq(budgets.currency, purchase.currency), eq(budgets.balanceStatus, "CURRENT"))).limit(1); if (!reservation || decimalUnits(reservation.budget_reservations.amount) !== decimalUnits(purchase.authorizedMaximum)) throw new RelayError("CAPABILITY_DENIED", "An exact current purchase budget reservation is required.", undefined, 403);
    const [credential] = await transaction.select().from(paymentCredentialReferences).where(and(eq(paymentCredentialReferences.accountId, input.accountId), eq(paymentCredentialReferences.id, purchase.credentialReferenceId), eq(paymentCredentialReferences.status, "ACTIVE"))).limit(1); if (!credential) throw new RelayError("CAPABILITY_DENIED", "Payment credential reference is unavailable.", undefined, 403);
    const [control] = await transaction.update(computerControlSessions).set({ controller: "HUMAN", humanPrincipalId: input.principalId, credentialEntryMode: true, fenceToken: sql`${computerControlSessions.fenceToken} + 1`, viewerEpoch: sql`${computerControlSessions.viewerEpoch} + 1`, updatedAt: timestamp }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, input.controlSessionId), eq(computerControlSessions.taskId, purchase.taskId), inArray(computerControlSessions.controller, ["AGENT", "PAUSED"]), eq(computerControlSessions.fenceToken, input.expectedFenceToken), eq(computerControlSessions.activeInputCount, 0), gt(computerControlSessions.expiresAt, timestamp))).returning(); if (!control) throw new RelayError("CAPABILITY_DENIED", "Protected checkout could not acquire exclusive human control.", undefined, 409);
    const action = actionIntentSchema.parse(purchase.actionSnapshot); const consumption = await consumeApprovalInTransaction(transaction, { accountId: input.accountId, requestId: approval.id, action, currentPolicyDecisionId: approval.policyDecisionId }, signer); const expiresAt = new Date(Math.min(Date.now() + Math.min(Math.max(input.permitTtlSeconds ?? 300, 30), 600) * 1_000, Date.parse(control.expiresAt), Date.parse(approval.expiresAt), Date.parse(reservation.budget_reservations.expiresAt))).toISOString(); const permitId = id("pcp");
    await transaction.insert(purchaseCheckoutPermits).values({ id: permitId, accountId: input.accountId, purchaseIntentId: purchase.id, principalId: input.principalId, controlSessionId: control.id, fenceToken: control.fenceToken, tokenHash: hashSecret(token), expiresAt }); await transaction.update(purchaseIntents).set({ status: "HUMAN_CHECKOUT", approvalDecisionId: consumption.approvalDecisionId, controlSessionId: control.id, updatedAt: timestamp }).where(and(eq(purchaseIntents.accountId, input.accountId), eq(purchaseIntents.id, purchase.id))); await transaction.insert(computerControlEvents).values({ id: id("cce"), accountId: input.accountId, controlSessionId: control.id, principalId: input.principalId, eventType: "purchase.checkout.started", fenceToken: control.fenceToken, details: { contentSuppressed: true, purchaseIntentId: purchase.id } }); await appendAuditRecordInTransaction(transaction, { accountId: input.accountId, actorPrincipalId: input.principalId, agentId: purchase.agentId, taskId: purchase.taskId, actionIntentId: purchase.actionIntentId, approvalDecisionId: consumption.approvalDecisionId, eventType: "money.checkout.protected", outcome: "HUMAN_CONTROL", details: { purchaseIntentId: purchase.id, controlSessionId: control.id, fenceToken: control.fenceToken, permitId } }, signer);
    return { permitToken: token, expiresAt, fenceToken: control.fenceToken, credentialReference: { id: credential.id, provider: credential.provider, displayLabel: credential.displayLabel } };
  });
}

async function requireCheckoutPermit(input: { accountId: string; principalId: string; purchaseIntentId: string; permitToken: string }, statuses: Array<"ACTIVE" | "COMMIT_READY">) {
  await requireMembership({ accountId: input.accountId, principalId: input.principalId, allowedRoles: ["OWNER", "ADMIN", "APPROVER"] }); const [binding] = await db().select({ permit: purchaseCheckoutPermits, purchase: purchaseIntents, control: computerControlSessions }).from(purchaseCheckoutPermits).innerJoin(purchaseIntents, and(eq(purchaseIntents.id, purchaseCheckoutPermits.purchaseIntentId), eq(purchaseIntents.accountId, purchaseCheckoutPermits.accountId))).innerJoin(computerControlSessions, and(eq(computerControlSessions.id, purchaseCheckoutPermits.controlSessionId), eq(computerControlSessions.accountId, purchaseCheckoutPermits.accountId))).where(and(eq(purchaseCheckoutPermits.accountId, input.accountId), eq(purchaseCheckoutPermits.purchaseIntentId, input.purchaseIntentId), eq(purchaseCheckoutPermits.principalId, input.principalId), eq(purchaseCheckoutPermits.tokenHash, hashSecret(input.permitToken)), inArray(purchaseCheckoutPermits.status, statuses), gt(purchaseCheckoutPermits.expiresAt, now()), eq(computerControlSessions.controller, "HUMAN"), eq(computerControlSessions.humanPrincipalId, input.principalId), eq(computerControlSessions.fenceToken, purchaseCheckoutPermits.fenceToken), eq(computerControlSessions.credentialEntryMode, true))).limit(1); if (!binding) throw new RelayError("CAPABILITY_DENIED", "Protected checkout permit is invalid, expired, or fenced.", undefined, 403); return binding;
}

export async function reviewHumanCheckout(input: { accountId: string; purchaseIntentId: string; principalId: string; permitToken: string; merchantId: string; merchantName: string; currency: string; finalAmount: string }, signer: AuditSigner) {
  assertNoRawPaymentCredentials(input); const parsed = z.object({ merchantId: z.string().min(1), merchantName: z.string().min(1), currency: currencySchema, finalAmount: positiveAmountSchema }).parse(input); const binding = await requireCheckoutPermit(input, ["ACTIVE"]); const changed = parsed.merchantId !== binding.purchase.merchantId || parsed.merchantName !== binding.purchase.merchantName || parsed.currency !== binding.purchase.currency || decimalUnits(parsed.finalAmount) !== decimalUnits(binding.purchase.requestedAmount);
  if (changed) { await withTransaction(async (transaction) => { await transaction.update(purchaseCheckoutPermits).set({ status: "REVOKED" }).where(and(eq(purchaseCheckoutPermits.accountId, input.accountId), eq(purchaseCheckoutPermits.id, binding.permit.id), eq(purchaseCheckoutPermits.status, "ACTIVE"))); await transaction.update(purchaseIntents).set({ status: "REVIEW_REQUIRED", finalAmount: parsed.finalAmount, updatedAt: now() }).where(and(eq(purchaseIntents.accountId, input.accountId), eq(purchaseIntents.id, binding.purchase.id), eq(purchaseIntents.status, "HUMAN_CHECKOUT"))); await transaction.update(computerControlSessions).set({ controller: "PAUSED", humanPrincipalId: null, credentialEntryMode: false, fenceToken: sql`${computerControlSessions.fenceToken} + 1`, viewerEpoch: sql`${computerControlSessions.viewerEpoch} + 1`, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, binding.control.id), eq(computerControlSessions.fenceToken, binding.control.fenceToken))); await appendAuditRecordInTransaction(transaction, { accountId: input.accountId, actorPrincipalId: input.principalId, agentId: binding.purchase.agentId, taskId: binding.purchase.taskId, actionIntentId: binding.purchase.actionIntentId, eventType: "money.checkout.changed", outcome: "REVIEW_REQUIRED", details: { purchaseIntentId: binding.purchase.id, expected: { merchantId: binding.purchase.merchantId, merchantName: binding.purchase.merchantName, currency: binding.purchase.currency, amount: binding.purchase.requestedAmount }, observed: parsed } }, signer); }); await releaseBudgetReservation({ accountId: input.accountId, reservationId: binding.purchase.budgetReservationId }, signer); return { commitReady: false as const, requiresNewIntentAndApproval: true as const }; }
  await withTransaction(async (transaction) => { const permit = await transaction.update(purchaseCheckoutPermits).set({ status: "COMMIT_READY" }).where(and(eq(purchaseCheckoutPermits.accountId, input.accountId), eq(purchaseCheckoutPermits.id, binding.permit.id), eq(purchaseCheckoutPermits.status, "ACTIVE"))).returning({ id: purchaseCheckoutPermits.id }); if (!permit.length) throw new RelayError("CAPABILITY_DENIED", "Checkout review was already consumed.", undefined, 409); await transaction.update(purchaseIntents).set({ status: "COMMIT_READY", finalAmount: parsed.finalAmount, updatedAt: now() }).where(and(eq(purchaseIntents.accountId, input.accountId), eq(purchaseIntents.id, binding.purchase.id), eq(purchaseIntents.status, "HUMAN_CHECKOUT"))); await appendAuditRecordInTransaction(transaction, { accountId: input.accountId, actorPrincipalId: input.principalId, agentId: binding.purchase.agentId, taskId: binding.purchase.taskId, actionIntentId: binding.purchase.actionIntentId, eventType: "money.checkout.reviewed", outcome: "COMMIT_READY", details: { purchaseIntentId: binding.purchase.id, merchantId: parsed.merchantId, currency: parsed.currency, finalAmount: parsed.finalAmount } }, signer); }); return { commitReady: true as const };
}

export async function recordHumanCheckoutOutcome(input: { accountId: string; purchaseIntentId: string; principalId: string; permitToken: string; outcome: "SUCCEEDED" | "EFFECT_UNKNOWN"; providerReference?: string; receiptData?: Record<string, unknown> }, signer: AuditSigner) {
  assertNoRawPaymentCredentials(input); const binding = await requireCheckoutPermit(input, ["COMMIT_READY"]); if (binding.purchase.status !== "COMMIT_READY" || !binding.purchase.finalAmount) throw new RelayError("CAPABILITY_DENIED", "Checkout has not passed final human review.", undefined, 409); if (input.outcome === "SUCCEEDED" && !input.providerReference) throw new RelayError("INVALID_INPUT", "A provider reference is required for a confirmed purchase.");
  const finalAmount = binding.purchase.finalAmount; const providerReference = input.providerReference;
  if (input.outcome === "SUCCEEDED") await reconcileBudgetReservation({ accountId: input.accountId, reservationId: binding.purchase.budgetReservationId, actualAmount: finalAmount, usageIdempotencyKey: `purchase:${binding.purchase.id}:confirmed`, source: "human-checkout", occurredAt: now() }, signer); else await markBudgetReservationUnknown({ accountId: input.accountId, reservationId: binding.purchase.budgetReservationId, reason: "Human checkout outcome could not be confirmed." }, signer);
  return await withTransaction(async (transaction) => { const consumed = await transaction.update(purchaseCheckoutPermits).set({ status: "CONSUMED", consumedAt: now() }).where(and(eq(purchaseCheckoutPermits.accountId, input.accountId), eq(purchaseCheckoutPermits.id, binding.permit.id), eq(purchaseCheckoutPermits.status, "COMMIT_READY"))).returning({ id: purchaseCheckoutPermits.id }); if (!consumed.length) throw new RelayError("CAPABILITY_DENIED", "Checkout outcome was already recorded.", undefined, 409); const status = input.outcome === "SUCCEEDED" ? "COMPLETED" : "EFFECT_UNKNOWN"; await transaction.update(purchaseIntents).set({ status, providerReference, completedAt: input.outcome === "SUCCEEDED" ? now() : null, updatedAt: now() }).where(and(eq(purchaseIntents.accountId, input.accountId), eq(purchaseIntents.id, binding.purchase.id), eq(purchaseIntents.status, "COMMIT_READY"))); let receiptId: string | undefined; if (input.outcome === "SUCCEEDED") { const receiptData = redactForEvidence(input.receiptData ?? {}); receiptId = id("prc"); await transaction.insert(purchaseReceipts).values({ id: receiptId, accountId: input.accountId, purchaseIntentId: binding.purchase.id, providerReference: providerReference!, merchantId: binding.purchase.merchantId, merchantName: binding.purchase.merchantName, amount: finalAmount, currency: binding.purchase.currency, receiptData, receiptHash: canonicalHash(receiptData) }); } await transaction.update(computerControlSessions).set({ controller: "PAUSED", humanPrincipalId: null, credentialEntryMode: false, fenceToken: sql`${computerControlSessions.fenceToken} + 1`, viewerEpoch: sql`${computerControlSessions.viewerEpoch} + 1`, updatedAt: now() }).where(and(eq(computerControlSessions.accountId, input.accountId), eq(computerControlSessions.id, binding.control.id), eq(computerControlSessions.fenceToken, binding.control.fenceToken))); await transaction.insert(computerControlEvents).values({ id: id("cce"), accountId: input.accountId, controlSessionId: binding.control.id, principalId: input.principalId, eventType: input.outcome === "SUCCEEDED" ? "purchase.checkout.confirmed" : "purchase.checkout.unknown", fenceToken: binding.control.fenceToken, details: { purchaseIntentId: binding.purchase.id, receiptId: receiptId ?? null, contentSuppressed: true } }); await appendAuditRecordInTransaction(transaction, { accountId: input.accountId, actorPrincipalId: input.principalId, agentId: binding.purchase.agentId, taskId: binding.purchase.taskId, actionIntentId: binding.purchase.actionIntentId, approvalDecisionId: binding.purchase.approvalDecisionId ?? undefined, eventType: "money.checkout.recorded", outcome: status, details: { purchaseIntentId: binding.purchase.id, receiptId: receiptId ?? null, providerReference: providerReference ?? null, resumeRequired: true } }, signer); return { status, receiptId, resumeRequired: true as const }; });
}

export async function listPurchaseIntents(accountId: string) { return await db().select().from(purchaseIntents).where(eq(purchaseIntents.accountId, accountId)).orderBy(asc(purchaseIntents.createdAt)); }
export async function listPurchaseReceipts(accountId: string) { return await db().select().from(purchaseReceipts).where(eq(purchaseReceipts.accountId, accountId)).orderBy(asc(purchaseReceipts.createdAt)); }
export async function listFinancialAccounts(accountId: string) { return await db().select().from(financialAccounts).where(eq(financialAccounts.accountId, accountId)).orderBy(asc(financialAccounts.createdAt)); }

export class SimulatedPurchaseExecutor {
  constructor(private readonly environment: "test") {}
  execute(input: { merchantId: string; merchantName: string; currency: string; finalAmount: string; outcome: "SUCCEEDED" | "EFFECT_UNKNOWN" }) { if (this.environment !== "test" || process.env.NODE_ENV === "production") throw new RelayError("CAPABILITY_DENIED", "The simulated purchase executor is test-only.", undefined, 403); assertNoRawPaymentCredentials(input); return { ...input, providerReference: input.outcome === "SUCCEEDED" ? `sim_${randomBytes(8).toString("hex")}` : undefined }; }
}
