import { z } from "zod";
import { errorResponse, requireApiUser, verifySameOrigin } from "@/lib/api";
import { dashboardAgent } from "@/lib/dashboard-agent";
import { executeCapability } from "@/lib/executor";
import { shareSandbox } from "@/lib/sandboxes";
import { recordActivity } from "@/lib/activity";

export async function POST(request: Request) { try { if (!verifySameOrigin(request)) return Response.json({ error: "Invalid request origin." }, { status: 403 }); const user = await requireApiUser(); const input = z.object({ agentId: z.string().min(1), ttlSeconds: z.number().int().min(60).max(86400).optional() }).parse(await request.json()); const principal = await dashboardAgent(user, input.agentId); return Response.json(await executeCapability({ principal, capability: "sandbox.create", action: "sandbox.create", provider: "SANDBOX", sessionId: `dashboard:${user.id}`, arguments: input })); } catch (error) { return errorResponse(error); } }
export async function DELETE(request: Request) { try { if (!verifySameOrigin(request)) return Response.json({ error: "Invalid request origin." }, { status: 403 }); const user = await requireApiUser(); const input = z.object({ agentId: z.string().min(1), sandboxId: z.string().min(1) }).parse(await request.json()); const principal = await dashboardAgent(user, input.agentId); return Response.json(await executeCapability({ principal, capability: "sandbox.destroy", action: "sandbox.destroy", provider: "SANDBOX", sessionId: `dashboard:${user.id}`, arguments: input })); } catch (error) { return errorResponse(error); } }
export async function PATCH(request: Request) { try { if (!verifySameOrigin(request)) return Response.json({ error: "Invalid request origin." }, { status: 403 }); const user = await requireApiUser(); const input = z.object({ sandboxId: z.string().min(1), agentId: z.string().min(1) }).parse(await request.json()); await shareSandbox(user.accountId, input.sandboxId, input.agentId); await recordActivity({ accountId: user.accountId, agentId: input.agentId, sessionId: `dashboard:${user.id}`, capability: "sandbox.share", provider: "SANDBOX", action: "sandbox.share", status: "SUCCESS", durationMs: 0, resourceType: "sandbox", resourceId: input.sandboxId }); return Response.json({ shared: true }); } catch (error) { return errorResponse(error); } }
