"use client";
import { useEffect,useState } from "react";
type State={state:string;agentName:string|null;bindingId:string|null;lastActivity:string|null;executionEnabled:boolean};
const descriptions:Record<string,string>={NOT_CONFIGURED:"Telegram is not configured for this owner. A deployment administrator must configure the dedicated bot, storage and executor.",READY_TO_PAIR:"Connect your private Telegram chat to the assigned Agent. Pairing grants permission to receive your requests and reply to this chat.",PAIRED:"Your private chat is connected to the assigned Agent.",REVOKED:"This connection is revoked. New work and replies are blocked. A new connection identity is required to pair again.",AGENT_UNAVAILABLE:"The assigned Agent is unavailable. Another Agent will not be substituted.",EXECUTION_DISABLED:"Pairing is active. Agent execution is disabled in this environment.",APPROVAL_WAITING:"A request needs your approval or recovery decision. Review the exact request in your private chat.",DELIVERY_FAILURE:"Work and delivery have separate states. A reply failed or its delivery is unknown; work will not rerun to resend it.",PROVIDER_ATTENTION:"The Telegram provider needs attention. An administrator must check the bot configuration."};
export function TelegramConnection(){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[pair,setPair]=useState<{url:string;expiresAt:string}|null>(null);
 async function refresh(){try{const response=await fetch("/api/v2/operator/telegram",{cache:"no-store"});if(!response.ok)throw new Error();setState(await response.json());setError("");}catch{setError("Connection status is unavailable. Try again.");}}
 useEffect(()=>{void refresh();},[]);
 async function change(operation:"pair"|"revoke"){
  setBusy(true);setError("");
  try{const response=await fetch("/api/v2/operator/telegram",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(operation==="pair"?{operation,grantOwnerChannel:true}:{operation,bindingId:state?.bindingId})});if(!response.ok)throw new Error();if(operation==="pair")setPair(await response.json());else{setPair(null);setConfirm(false);}await refresh();}catch{setError("The connection could not be changed. Check its current status and try again.");}finally{setBusy(false);}
 }
 return <section className="v2-panel v2-section-gap" aria-labelledby="telegram-heading"><div className="v2-panel-head"><div><span>PRIVATE OWNER CHANNEL</span><h2 id="telegram-heading">Telegram</h2></div></div><div style={{padding:"0 24px 24px",overflowWrap:"anywhere"}}>
  {!state&&!error?<p role="status">Loading connection status…</p>:null}
  {state?<><p><strong>{state.state.toLowerCase().replaceAll("_"," ")}</strong>{state.agentName?` · ${state.agentName}`:""}</p><p>{descriptions[state.state]??"Connection status requires review."}</p>{state.lastActivity?<p>Last activity: <time dateTime={state.lastActivity}>{new Date(state.lastActivity).toLocaleString()}</time></p>:null}</>:null}
  {error?<p role="alert">{error}</p>:null}
  <div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button type="button" disabled={busy} onClick={()=>void refresh()}>Refresh status</button>{state?.state==="READY_TO_PAIR"?<button type="button" disabled={busy} onClick={()=>void change("pair")}>{busy?"Preparing pairing…":"Grant channel access and pair"}</button>:null}{state?.bindingId&&!confirm?<button type="button" disabled={busy} onClick={()=>setConfirm(true)}>Revoke connection</button>:null}</div>
  {pair?<div role="status"><p>Open this one-use pairing link in your private Telegram chat. It expires at {new Date(pair.expiresAt).toLocaleTimeString()}. Keep it private.</p><a href={pair.url} target="_blank" rel="noreferrer noopener">Pair in Telegram</a><p>After Telegram accepts pairing, refresh the status here.</p></div>:null}
  {confirm?<div role="group" aria-label="Confirm Telegram revocation"><p>Revoke this connection? New work and queued replies will be blocked. Existing Run history remains available.</p><button type="button" disabled={busy} onClick={()=>void change("revoke")}>{busy?"Revoking…":"Confirm revocation"}</button>{" "}<button type="button" disabled={busy} onClick={()=>setConfirm(false)}>Keep connection</button></div>:null}
 </div></section>;
}
